/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGQUKJF',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'ageWithSui',
  structures: ['Subj. + Number + 岁', 'Subj. + Number + 岁 + 半'],
  description:
    'Use 岁 (suì) to give a person\'s age, similar to how we say "years old" in English. There are a details that work differently from English, however.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([regexMatchLocs(sentence.text, /[零一二三四五六七八九十百千万亿两0-9]+(岁)/)]),
  examples: [
    {
      zh: '我20岁。',
      en: 'I am 20 years old.',
      src: allSetSrc,
    },
    {
      zh: '我儿子一岁。',
      en: 'My son is one year old.',
      src: allSetSrc,
    },
    {
      zh: '我妈妈今年45岁。',
      en: 'My mother is 45 years old this year.',
      src: allSetSrc,
    },
    {
      zh: '你爷爷今年80岁吗？',
      en: 'Is your grandpa eighty years old this year?',
      src: allSetSrc,
    },
    {
      zh: '他女朋友也20岁吗？',
      en: 'Is his girlfriend also twenty years old?',
      src: allSetSrc,
    },
    {
      zh: '我的孩子一岁。',
      en: 'My child is one year old.',
      src: allSetSrc,
    },
    {
      zh: '她两岁半。',
      en: 'She is two and a half years old.',
      src: allSetSrc,
    },
    {
      zh: '我儿子一岁半。',
      en: 'My son is one and a half years old.',
      src: allSetSrc,
    },
  ],
};
