/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGTYJ3E',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'budanErqie',
  structures: [
    'Subj. + 不但 + Adj. / Verb， 而且 + Adj. / Verb',
    'Subj. + 不但 +  Adj. / Verb， 而且 + Adj. / Verb',
    '不但 + Subj. 1 + Adj. / Verb， 而且 + Subj. 2 + Adj. / Verb',
  ],
  description:
    '"不但⋯⋯，而且⋯⋯" (bùdàn..., érqiě...) is a very commonly used pattern that indicates "not only, ... but also...."',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([regexMatchLocs(sentence.text, /(不但)[^而且]+(而且)/)]),
  examples: [
    {
      zh: '这种菜不但好吃，而且有营养。',
      en: 'This kind of vegetable is not only delicious, but nutritious as well.',
      src: allSetSrc,
    },
    {
      zh: '她不但聪明，而且很努力。',
      en: 'She is not only smart, but also very hard-working.',
      src: allSetSrc,
    },
    {
      zh: '他不但做完了，而且做得非常好。',
      en: 'Not only did he finish, but he also did it extremely well.',
      src: allSetSrc,
    },
    {
      zh: '我不但会做饭，而且会洗衣服。',
      en: 'Not only can I cook, but I can also do the laundry.',
      src: allSetSrc,
    },
    {
      zh: '不但我会做饭，而且我妹妹也会做饭。',
      en: 'Not only can I cook, but my little sister can as well.',
      src: allSetSrc,
    },
  ],
};
