/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG8R2V8',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'buDong',
  name: 'Subj. +  Verb + 不懂',
  description:
    "Chinese learners often have to express that they don't understand something, especially in the beginning when they start learning. One of the ways to express that is to use the 不懂 (bù dǒng) verb complement.",
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(不懂)/)]);
  },
  examples: [
    {
      zh: '我看不懂这本书。',
      en: "I don't understand the book.",
      src: allSetSrc,
    },
    {
      zh: '孩子们看不懂你写的汉字。',
      en: "Kids don't understand the characters that you wrote.",
      src: allSetSrc,
    },
    {
      zh: '你看不懂我的邮件吗？',
      en: 'Do you not understand my emails?',
      src: allSetSrc,
    },
    {
      zh: '老板的中文说得很好，可是他看不懂中文报纸。',
      en:
        "The boss speaks very good Chinese, but he doesn't understand Chinese newspapers.",
      src: allSetSrc,
    },
    {
      zh: '我听不懂上海话。',
      en: "I don't understand Shanghai dialect.",
      src: allSetSrc,
    },
    {
      zh: '你们听不懂我的话吗？',
      en: 'Do you not understand what I say?',
      src: allSetSrc,
    },
    {
      zh: '我听不懂你说的英语。',
      en: "I don't understand your English.",
      src: allSetSrc,
    },
    {
      zh: '我们都听不懂你的意思。',
      en: 'None of us understand what you mean.',
      src: allSetSrc,
    },
    {
      zh: '很多人读不懂这本书。',
      en: "Many people don't understand this book.",
      src: allSetSrc,
    },
    {
      zh: '这个句子很难，学生们都读不懂。',
      en: 'This sentence is very difficult. None of the students understand.',
      src: allSetSrc,
    },
  ],
};
