/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGQAN74',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'chahenduo',
  structures: ['Subj. + 差 很 多', 'A + 跟 / 和 +  B + 差很多'],
  description:
    "You might be used to thinking of 差不多 (chàbùduō) as a single word, and that's totally OK. But if you want to negate the whole idea of rough equivalency, then you need to think of it as a phrase and use 差很多 (chà hěn duō). Not surprisingly, it's a little less versatile than 差不多 (chàbùduō).",
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(差很多)/),
      regexMatchLocs(sentence.text, /((?:跟|和))[^差很多]+(差很多)/),
    ]),
  examples: [
    {
      zh: '这两家店的东西价格差很多。',
      en: 'There is a big difference in price between these two shops.',
      src: allSetSrc,
    },
    {
      zh: '我和我男朋友的年龄差很多。',
      en: "There is a big difference between my age and my boyfriend's age.",
      src: allSetSrc,
    },
    {
      zh: '中国文化和西方文化差很多。',
      en: 'Chinese culture and western culture are quite different.',
      src: allSetSrc,
    },
    {
      zh: '我的收入跟我老板的收入差很多。',
      en: "There is a huge difference between my income and my boss'.",
      src: allSetSrc,
    },
    {
      zh: '这两个词的意思差不多，但是用法差很多。',
      en:
        'The meanings of these two words are basically the same, but their usages are very different.',
      src: allSetSrc,
    },
  ],
};
