/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGMD0YY',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'chufei',
  name: 'y，除非 x',
  description:
    '除非 (chúfēi) can be used as a conjunction, and means "unless." 否则 (fǒuzé) or 不然 (bùrán) often appear in the following phrase, to form a construction meaning "unless x, otherwise y":',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(除非)[^否然]+(否则|不然)?[^才]+(才)?/)]);
  },
  examples: [
    {
      zh: '老板不给你加薪，除非你表现很好。',
      en: "The boss won't give you a raise unless you perform well.",
      src: allSetSrc,
    },
    {
      zh: '公司不允许员工请假，除非理由很充分。',
      en:
        "The company won't allow it's staff time off unless their reason is good enough.",
      src: allSetSrc,
    },
    {
      zh: '欧洲的经济无法恢复正常，除非希腊债务问题得以解决。',
      en:
        "Europe will be unable to normalize it's economy, unless Greece resolves it's debt problem.",
      src: allSetSrc,
    },
    {
      zh: '我们会破产，除非能申请到银行贷款。',
      en: "We're going to go bankrupt unless we are able to apply for a bank loan.",
      src: allSetSrc,
    },
    {
      zh: '除非你表现很好，否则老板不给你加薪。',
      en: "Unless your performance is good, the boss won't give you a raise.",
      src: allSetSrc,
    },
    {
      zh: '除非理由很充分，否则公司不允许员工请假。',
      en: "Unless the reason is good, the company won't give its staff time off.",
      src: allSetSrc,
    },
    {
      zh: '除非希腊债务问题得以解决，不然欧洲的经济无法恢复正常。',
      en:
        "Unless Greece resolves it's debt problem, Europe won't be able to bring its economy back to normal.",
      src: allSetSrc,
    },
    {
      zh: '除非能申请到银行贷款，否则我们就会破产。',
      en: "Unless we can apply for a bank loan, we're going to go bankrupt.",
      src: allSetSrc,
    },
    {
      zh: '除非理由很充分，公司才允许员工请假。',
      en: 'Only if the reason is good enough will the company give its staff time off.',
      src: allSetSrc,
    },
    {
      zh: '除非你表现很好，老板才给你加薪。',
      en: "Unless your performance is good, the boss won't give you a raise.",
      src: allSetSrc,
    },
    {
      zh: '除非希腊债务问题得以解决，欧洲的经济才恢复正常。',
      en:
        'Only if Greece resolves its debt problem will Europe be able to bring its economy back to normal.',
      src: allSetSrc,
    },
    {
      zh: '除非能申请到银行贷款，我们才不会破产。',
      en: 'Only if we can apply for the loan will we be able to avoid going bankrupt.',
      src: allSetSrc,
    },
  ],
};
