/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGHFPGG',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'chule',
  structures: [
    '除了 + Noun Phrase + (以外) + Noun Phrase + 都 + Verb',
    '除了 + Noun Phrase + (以外) + Noun Phrase + 也 / 还 + Verb',
  ],
  description:
    'Using 除了 (chúle)⋯⋯ 以外 (yǐwài) will help you spruce up your sentences when you want to express "except," "besides," and "in addition."  You may feel that "except" has a pretty different meaning form the other two. Well, read on!',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(除了)[^以外]+((?:以外)?)[^都]+(都)/),
      regexMatchLocs(sentence.text, /(除了)[^以外]+((?:以外)?)[^也还]+((?:也|还))/),
    ]),
  examples: [
    {
      zh: '除了妈妈以外，我们全家都去香港。',
      en: 'Except for mother, the whole family went to Hong Kong.',
      src: allSetSrc,
    },
    {
      zh: '除了白酒以外，他什么酒都喝。',
      en: 'He will drink anything except white wine.',
      src: allSetSrc,
    },
    {
      zh: '除了星期天以外，我们每天都上班。',
      en: 'Except for Sunday, we work every day.',
      src: allSetSrc,
    },
    {
      zh: '除了海南岛以外，我还想去台湾旅行。',
      en: 'In addition to Hainan Island, I also want to travel to Taiwan.',
      src: allSetSrc,
    },
    {
      zh: '除了牛肉以外，她也很喜欢吃鸡肉。',
      en: 'In addition to beef, she also likes to chicken.',
      src: allSetSrc,
    },
    {
      zh: '中国的功夫明星除了成龙，李连杰也很有名。',
      en: 'In addition to Jackie Chen, Jet Li is also very famous as a kung fu star.',
      src: allSetSrc,
    },
  ],
};
