/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG1MD4N',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'comparisonXiang',
  structures: [
    'Noun 1 + 像 + Noun 2 + 一样 + Adj. / Verb',
    'Noun 1 + 像 + Noun 2 + 这么 / 那么 + Adj. / Verb',
    'Noun 1 + 不像 + Noun 2 + 这么 / 那么 + Adj. / Verb',
    'Noun 1 + 没有 + Noun 2 + 这么 / 那么 + Adj. / Verb',
  ],
  description:
    '像  (xiàng) is used to compare a specific characteristic of two things or people, and can be used in the following structure:',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(不?像|没有?)[^一样]+(一样)/),
      regexMatchLocs(sentence.text, /(不?像|没有?)[^么]*((?:这么|那么))/),
    ]),
  examples: [
    {
      zh: '你怎么像我妈一样啰嗦!',
      en: 'Why do you sound as nagging as my mom does!',
      src: allSetSrc,
    },
    {
      zh: '他生气的时候会像疯子一样大叫。',
      en: 'He would scream like a lunatic when he gets angry.',
      src: allSetSrc,
    },
    {
      zh: '这个男老师不像那个女老师那么严格。',
      en: 'This man teacher is not as strict as that woman teacher.',
      src: allSetSrc,
    },
    {
      zh: '我们没有你那么喜欢孩子。',
      en: "We don't like kids as much as you do.",
      src: allSetSrc,
    },
  ],
};
