/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGGGIW8',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'congDao',
  name: '从 + Time 1 + 到 + Time 2',
  description:
    '从⋯⋯ 到⋯⋯(cóng... dào...) is used in the same way as "from... to..." is used in English, and can be used both for times and places.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(从)[^到]+(到)/)]),
  examples: [
    {
      zh: '从2004年到2008年',
      en: 'from 2004 to 2008',
      src: allSetSrc,
    },
    {
      zh: '从一号到五号都在下雨。',
      en: "From the first to the fifth, it's been raining non-stop.",
      src: allSetSrc,
    },
    {
      zh: '老板从周二到周五都要出差。',
      en: 'From Tuesday until Friday the boss will go on a business trip.',
      src: allSetSrc,
    },
    {
      zh: '她从18岁到现在都一个人住。',
      en: "She's lived alone since she was 18 until now.",
      src: allSetSrc,
    },
    {
      zh: '你不能从早到晚不吃东西。',
      en: "You can't eat nothing from morning to night.",
      src: allSetSrc,
    },
    {
      zh: '从南京西路到南京东路',
      en: 'from West Nanjing Road to East Nanjing Road',
      src: allSetSrc,
    },
    {
      zh: '从酒店到机场不太远。',
      en: 'From the hotel to the airport is not too far.',
      src: allSetSrc,
    },
    {
      zh: '从上海到北京要几个小时。',
      en: 'From Shanghai to Beijing it takes a few hours.',
      src: allSetSrc,
    },
    {
      zh: '从你家到机场可以坐地铁吗？',
      en: 'From your place  to the airport, can I take the subway?',
      src: allSetSrc,
    },
    {
      zh: '从这里到我们公司，你会看见很多美女。',
      en: "From here to our company, you'll see many beautiful girls.",
      src: allSetSrc,
    },
  ],
};
