/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG7AE5C',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'definingScope',
  name: '级别 / 次序 / 数目 + 以上 / 以下',
  description: '',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(以上|以下)/),
      regexMatchLocs(text, /(以内|以外)/),
    ]);
  },
  examples: [
    {
      zh: '我老家空气还不错，PM2.5一般在五十以下。',
      en: 'The air in my hometown is good. PM 2.5 is generally under 50.',
      src: allSetSrc,
    },
    {
      zh: '我们需要有两年以上工作经验的人。',
      en: 'We need people with two years of working experience or more.',
      src: allSetSrc,
    },
    {
      zh: '十岁以下的孩子不用买票。',
      en: 'Children under the age of 10 do not need to buy tickets.',
      src: allSetSrc,
    },
    {
      zh: '我们出差都住三星级以上的酒店。',
      en:
        'When we go on business trips, we stay at hotels with at least a 3-star rating.',
      src: allSetSrc,
    },
    {
      zh: '这里的冬天气温都在零度以下。',
      en: 'This winter, the temperature has been less than 0 degrees.',
      src: allSetSrc,
    },
    {
      zh: '以下就谈谈这个问题应该怎么解决。',
      en:
        'In the following conversation, we will discuss how we should resolve this problem.',
      src: allSetSrc,
    },
    {
      zh: '以上只是我个人的看法。',
      en: 'The following is just my personal opinion.',
      src: allSetSrc,
    },
    {
      zh: '两天以内必须完成。',
      en: 'Must be completed in two days or less.',
      src: allSetSrc,
    },
    {
      zh: '半小时以内能送到吗？',
      en: 'Can you deliver in 30 minutes or less?',
      src: allSetSrc,
    },
    {
      zh: '这个大楼50米以内不能停车。',
      en: 'You cannot park within 50 meters of this building.',
      src: allSetSrc,
    },
    {
      zh: '请你站在两米以外的地方。',
      en: 'Can you stop 2 meters outside of this place?',
      src: allSetSrc,
    },
    {
      zh: '这个区以外的几个区都不太发达。',
      en: 'All of the areas outside this one are not very developed.',
      src: allSetSrc,
    },
    {
      zh: '除了这个以外，还有一点也很重要。',
      en: 'Aside from this, there is still one point that is very important.',
      src: allSetSrc,
    },
  ],
};
