/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGWN185',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'deShihou',
  name: '(Subj.) + Verb / Adj. + 的 时候, ....',
  description:
    'In English, if we are reflecting on a past time, we often say, "when I was a child" or "when I was in school." In Chinese, this can also be expressed by using 的时候 (de shíhou).',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(的时候)/)]);
  },
  examples: [
    {
      zh: '你不在的时候，我会想你。',
      en: "When you are not here, I'll miss you.",
      src: allSetSrc,
    },
    {
      zh: '我上大学的时候，有很多朋友。',
      en: 'When I was in college, I had a lot of friends.',
      src: allSetSrc,
    },
    {
      zh: '上课的时候不要吃东西。',
      en: "Don't eat when you are in class.",
      src: allSetSrc,
    },
    {
      zh: '老板工作的时候喜欢喝咖啡。',
      en: 'When the boss works, he likes to drink coffee.',
      src: allSetSrc,
    },
    {
      zh: '我生气的时候，请你不要笑。',
      en: "Please don't laugh when I'm angry.",
      src: allSetSrc,
    },
    {
      zh: '妈妈不在家的时候，我自己做饭。',
      en: 'When mom is not home, I cook for myself.',
      src: allSetSrc,
    },
    {
      zh: '开会的时候不要聊天。',
      en: "Don't chat when you are in a meeting.",
      src: allSetSrc,
    },
    {
      zh: '吃东西的时候不要说话。',
      en: "Don't talk when eating.",
      src: allSetSrc,
    },
    {
      zh: '你开车的时候会打电话吗？',
      en: "Do you talk on the phone when you're driving?",
      src: allSetSrc,
    },
    {
      zh: '走路的时候不要玩手机。',
      en: "Don't play with your phone while walking.",
      src: allSetSrc,
    },
  ],
};
