/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGD3C4S',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'emphasizingNegationWithYou',
  name: '又 + 不 / 没 + Verb / Adj.',
  description:
    'One of the many versatile uses of 又 is to emphasize negation, giving your negative sentence a little kick!',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(又(?:不|没))/)]),
  examples: [
    {
      zh: '我又不知道，问我干吗？',
      en: "I definitely don't know. Why ask me?",
      src: allSetSrc,
    },
    {
      zh: '你又不忙，为什么不来？',
      en: "You're not busy. Why not come?",
      src: allSetSrc,
    },
    {
      zh: '我又没做错，你为什么生我的气？',
      en: "I didn't do anything wrong! Why are you mad at me?",
      src: allSetSrc,
    },
    {
      zh: '又不是我做的，看我干吗？',
      en: "I definitely didn't do that. Why are you looking at me?",
      src: allSetSrc,
    },
    {
      zh: '今天又不下雨，为什么要带伞？',
      en: "It's not going to rain today. Why are you bringing the umbrella?",
      src: allSetSrc,
    },
    {
      zh: '又不是你的事，你管那么多干吗？',
      en: "It's not any of your business. Why do you care so much?",
      src: allSetSrc,
    },
    {
      zh: '我又不是故意的，你不要这么生气。',
      en: "It really wasn't on purpose. Don't be so mad.",
      src: allSetSrc,
    },
  ],
};
