/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG13ALM',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'everyDou',
  name: '谁 + 都 + Verb Phrase',
  description:
    'This grammar point is not about how to use 每 (měi) to mean "every," but rather how to combine question words with 都 (dōu) to make words and phrases like "everywhere" or "everyone." You may have learned this same pattern for expressing "everything," but now it\'s time to extend it.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /((?:谁|哪儿|哪里)都)/),
      regexMatchLocs(sentence.text, /(什么|多少|怎么)[^都]{0,4}(都)/),
    ]),
  examples: [
    {
      zh: '谁都喜欢美食。',
      en: 'Everyone likes delicious food.',
      src: allSetSrc,
    },
    {
      zh: '这个地方谁都可以进。',
      en: 'Everyone can go inside this place.',
      src: allSetSrc,
    },
    {
      zh: '谁都不相信他说的话。',
      en: 'No one believes what he said.',
      src: allSetSrc,
    },
    {
      zh: '谁都不希望发生这样的事。',
      en: 'No one wants this kind of thing to happen.',
      src: allSetSrc,
    },
    {
      zh: '谁都没办法证明他拿了公司的钱。',
      en: "No one can prove that he took the company's money.",
      src: allSetSrc,
    },
    {
      zh: '你家太乱了，哪儿都是脏衣服。',
      en: 'Your place is so messy. Dirty clothes are everywhere.',
      src: allSetSrc,
    },
    {
      zh: '昨天运动得太厉害了，现在哪儿都疼。',
      en: 'I exercised too strenuously yesterday. Now everywhere hurts.',
      src: allSetSrc,
    },
    {
      zh: '我太累了，哪儿都不想去。',
      en: "I'm too tired. I don't want to go anywhere.",
      src: allSetSrc,
    },
    {
      zh: '你什么时候来都行。',
      en: 'You can come anytime.',
      src: allSetSrc,
    },
    {
      zh: '什么时候开始都不晚。',
      en: "It's never too late to begin.",
      src: allSetSrc,
    },
    {
      zh: '我家什么时候都有人在。',
      en: 'There is always someone at home.',
      src: allSetSrc,
    },
    {
      zh: '多少钱都买不到这个东西。',
      en: "You can't buy this thing at any price.",
      src: allSetSrc,
    },
    {
      zh: '你想吃多少都可以。',
      en: 'You can eat however much you want.',
      src: allSetSrc,
    },
    {
      zh: '这些是免费的，我们拿多少都没问题。',
      en: 'These are all free. We can take however much we want.',
      src: allSetSrc,
    },
    {
      zh: '我想怎么做都可以吗？',
      en: 'Is it OK if I do however I want?',
      src: allSetSrc,
    },
    {
      zh: '别人怎么想都不重要。',
      en: "It doesn't matter however other people think.",
      src: allSetSrc,
    },
    {
      zh: '这件衣服怎么穿都好看。',
      en: 'This clothing looks good however you wear it.',
      src: allSetSrc,
    },
  ],
};
