/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGGOUJB',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingAlmostUsingChadianMei',
  structures: ['Subj. + 差点 + 没 + Verb Phrase'],
  description:
    "Logically, 差点没 is not that different from 差点.  In fact, you shouldn't think of it as a single word; think of the 没 as belonging to what follows 差点 and it makes more sense.  Still, it can be a little confusing, and is worth a closer look.",
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(差点儿?没)/)]),
  examples: [
    {
      zh: '我差点儿没想起来。',
      en: 'I almost forgot it.',
      src: allSetSrc,
    },
    {
      zh: '我差点没赶上火车。',
      en: "I didn't miss the train.",
      src: allSetSrc,
    },
    {
      zh: '他差点没通过考试。',
      en: 'He barely passed the examination.',
      src: allSetSrc,
    },
    {
      zh: '排队的人太多了，差点儿没买到。',
      en: "The waiting line is too long. I almost didn't get it.",
      src: allSetSrc,
    },
  ],
};
