/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGNGEU8',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingAboutToHappenWithLe',
  name: '快+ Verb / Verb Phrase + 了',
  description:
    'Remember that 了 (le) is not only for the past! When something is about to happen, you can also indicate this using 了 (le).  Normally it is paired with a 快 (kuài), 快要(kuàiyào) or a 要 (yào). This is a special form of using 了 to indicate a change of situation.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(快)[^了]+(了)/),
      regexMatchLocs(text, /(快要)[^了]+(了)/),
      regexMatchLocs(text, /(要)[^了]+(了)/),
    ]);
  },
  examples: [
    {
      zh: '我们快到了。',
      en: "We're almost there.",
      src: allSetSrc,
    },
    {
      zh: '快下雨了，我们走吧。',
      en: "It's going to rain soon. Let's go.",
      src: allSetSrc,
    },
    {
      zh: '快要过年了，你什么时候回家？',
      en: "It's almost Chinese New Year. When are you going back to your hometown?",
      src: allSetSrc,
    },
    {
      zh: '我女朋友快要过生日了。',
      en: 'My girlfriend is about to have her birthday.',
      src: allSetSrc,
    },
    {
      zh: '快下车了，你再等一会儿。',
      en: "We're about to get off. Just wait a little while.",
      src: allSetSrc,
    },
    {
      zh: '天快黑了。',
      en: 'It’s almost getting dark.',
      src: allSetSrc,
    },
    {
      zh: '我快好了。',
      en: "I'm almost ready.",
      src: allSetSrc,
    },
    {
      zh: '饭快凉了。',
      en: 'The food is about to be cold.',
      src: allSetSrc,
    },
    {
      zh: '这些脏衣服快臭了。',
      en: 'These dirty clothes are about to smell bad.',
      src: allSetSrc,
    },
    {
      zh: '不能再喝了，我快醉了。',
      en: "I can't drink another, I am almost drunk.",
      src: allSetSrc,
    },
    {
      zh: '我要生气了！',
      en: "I'm going to get angry!",
      src: allSetSrc,
    },
    {
      zh: '他们的孩子要出生了。',
      en: 'Their child is about to be born.',
      src: allSetSrc,
    },
    {
      zh: '9点了，超市要关门了。',
      en: "It's 9 o'clock. The supermarket is about to close.",
      src: allSetSrc,
    },
    {
      zh: '我最好的朋友要结婚了！',
      en: 'My best friend is about to get married!',
      src: allSetSrc,
    },
    {
      zh: '圣诞节要到了，你有什么打算？',
      en: "It's almost Christmas. What plans do you have?",
      src: allSetSrc,
    },
  ],
};
