/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGDF1F7',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingQuiteWithTing',
  name: '挺 + Adj. + 的',
  description:
    '挺 can be used before an adjective to mean "quite," or "rather," or "pretty," as in "pretty good."',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(挺)[^的]+(的)/)]);
  },
  examples: [
    {
      zh: '这件衣服大小挺合适的。',
      en: 'The size of this piece of clothes is quite suitable.',
      src: allSetSrc,
    },
    {
      zh: '我觉得你妈妈挺年轻的。',
      en: 'I think your mom is quite young.',
      src: allSetSrc,
    },
    {
      zh: '你不觉得他挺帅的吗？',
      en: "You don't think he's quite handsome?",
      src: allSetSrc,
    },
    {
      zh: '他们家挺有钱的，但是他不像有钱人。',
      en: "Their family is quite rich, but he doesn't like like a rich person.",
      src: allSetSrc,
    },
    {
      zh: '大学生毕业找工作的压力挺大的。',
      en: 'College graduates who are looking for jobs are under quite a lot of pressure.',
      src: allSetSrc,
    },
    {
      zh: '这份工作压力不大，挺适合女孩子的。',
      en: "This job doesn't give you much stress.It quite suits girls.",
      src: allSetSrc,
    },
    {
      zh: '我们一直都挺想你的。',
      en: 'We always miss you.',
      src: allSetSrc,
    },
    {
      zh: '我真的挺讨厌你老板的。',
      en: 'I really hate your boss.',
      src: allSetSrc,
    },
    {
      zh: '你不是挺喜欢他的吗？为什么要跟他分手？',
      en: "Don't you really like him? Why do you want to break up with him?",
      src: allSetSrc,
    },
    {
      zh: '他不是挺爱运动的吗？怎么不跟我们一起去爬山？',
      en: "Doesn't he love to do sports? Why didn't he climb the mountain with us?",
      src: allSetSrc,
    },
  ],
};
