/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG72HKP',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingRatherWithBijiao',
  name: 'Subj. + 比较 + Adj.',
  description:
    'It\'s rather nice to be able to read an article on how to use 比较 to mean "rather." And here it is!',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(比较)/)]);
  },
  examples: [
    {
      zh: '她比较聪明。',
      en: 'She is rather intelligent.',
      src: allSetSrc,
    },
    {
      zh: '你比较胖。',
      en: "You're rather fat.",
      src: allSetSrc,
    },
    {
      zh: '这件事情比较复杂。',
      en: 'This matter is rather complicated.',
      src: allSetSrc,
    },
  ],
};
