/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGVMC4B',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingTheSelfevidentWithMa',
  name: 'Statement + 嘛',
  description:
    'The particle 嘛 (ma) is a sentence-final particle identical in pronunciation to the simple "yes/no question" particle 吗 (ma) you learned back in the day, but with a rather different function.  It can be used when the speaker feels what he is saying is obvious (from his point of view).',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(嘛)/)]);
  },
  examples: [
    {
      zh: '你的妹妹很漂亮嘛。',
      en: 'Your sister is pretty.',
      src: allSetSrc,
    },
    {
      zh: '中国人口很多嘛。',
      en: 'The Chinese population is huge.',
      src: allSetSrc,
    },
    {
      zh: '美国人很开放嘛。',
      en: 'Americans are very open-minded.',
      src: allSetSrc,
    },
    {
      zh: '大熊猫嘛，孩子们都很喜欢。',
      en: 'Pandas. All children like them.',
      src: allSetSrc,
    },
    {
      zh: '男人嘛，总是要喝点酒，抽点烟。',
      en: "Men. They're always going to drink and smoke.",
      src: allSetSrc,
    },
  ],
};
