/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGB6L4M',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingEveryWithMei',
  name: '每 + Measure Word + Noun + 都',
  description:
    'In this article we will look at the structure for saying "every" in Chinese, which is slightly more involved than just throwing in the word 每 (měi).',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(每)[^都]+(都)/)]);
  },
  examples: [
    {
      zh: '每个菜都好吃。',
      en: 'Every dish is delicious.',
      src: allSetSrc,
    },
    {
      zh: '你每个人都认识吗？',
      en: 'Do you know every person?',
      src: allSetSrc,
    },
    {
      zh: '老板每个月都出差。',
      en: 'The boss goes on business trips every month.',
      src: allSetSrc,
    },
    {
      zh: '他每天都不吃早饭。',
      en: 'Every morning he skips breakfast.',
      src: allSetSrc,
    },
    {
      zh: '他每年都来中国。',
      en: 'He comes to China every year.',
      src: allSetSrc,
    },
    {
      zh: '我每个星期都给妈妈打电话。',
      en: 'I give mom a phone call every week.',
      src: allSetSrc,
    },
    {
      zh: '这个班的每个学生都很聪明。',
      en: 'Each of the students in this class are very smart.',
      src: allSetSrc,
    },
    {
      zh: '老师每天都给我们很多作业。',
      en: 'Every day the teacher gives us a lot of homework.',
      src: allSetSrc,
    },
    {
      zh: '我们每周都要开会。',
      en: 'Every week we need to have a meeting.',
      src: allSetSrc,
    },
    {
      zh: '他们每个周末都去公园。',
      en: 'Every weekend they go to the park.',
      src: allSetSrc,
    },
  ],
};
