/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG9B210',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingAboutToWithJiuyao',
  name: '就要 + Verb Phrase + 了',
  description:
    '就要 (jiùyào) is similar to 快要 (kuàiyào), meaning "about to." They are interchangeable in some cases. But there is a major difference that you need to take a good look at. 快要 (kuài yào) is generally "about to" [happen], but 就要 (jiù yào) could be used to mark a more specific time. 要 (yào) here can be omitted. For this one, you wouldn\'t normally use "about to" for this English translation, but the feeling is nevertheless that the impending event is coming up fast.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(就要)[^了]+(了)/),
      regexMatchLocs(text, /(还有)[^就要]+(就要?)[^了]+(了)/),
    ]);
  },
  examples: [
    {
      zh: '我就要饿死了。',
      en: "I'm about to starve to death.",
      src: allSetSrc,
    },
    {
      zh: '他们就要结婚了。',
      en: 'They are about to get married.',
      src: allSetSrc,
    },
    {
      zh: '就要下课了，还有别的问题吗？',
      en: 'The class is almost over. Are there any other questions?',
      src: allSetSrc,
    },
    {
      zh: '还有十天宝宝就一岁了。',
      en: 'In ten more days, the baby will be one year old.',
      src: allSetSrc,
    },
    {
      zh: '还有十分钟就下班了。',
      en: 'In 10 more minutes I get off work.',
      src: allSetSrc,
    },
    {
      zh: '还有五天就要放假了。',
      en: 'In 10 more days, I go on vacation.',
      src: allSetSrc,
    },
    {
      zh: '还有一个月就要过年了。',
      en: 'In another month it will be Chinese New Year.',
      src: allSetSrc,
    },
    {
      zh: '还有两个星期就要考试了。',
      en: "We're just two weeks away from the test date.",
      src: allSetSrc,
    },
  ],
};
