/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG50341',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingIncludingWithBaokuo',
  name: 'Subj. + 包括 + Obj.1 ( , + Obj.2, Obj.3 ... )',
  description:
    '"包括" can be used to mean "including" in English. It can be used with "在内一共" or just "一共" to express "all together" or "in total"',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(包括)/),
      regexMatchLocs(text, /(包括)[^共括]+((?:在内)?一共)/),
    ]);
  },
  examples: [
    {
      zh: '他说“咱们”，当然包括你。',
      en: 'He said "us". That certainly includes you.',
      src: allSetSrc,
    },
    {
      zh: '我每个月的房租不包括水电费。',
      en: 'My monthly rent does not include my water and electric bill.',
      src: allSetSrc,
    },
    {
      zh: '公司的福利包括很多方面。',
      en: "The company's welfare benefits includes many aspects.",
      src: allSetSrc,
    },
    {
      zh: '他对很多话题都很感兴趣，包括政治。',
      en: 'He finds many topics of conversation interesting, including politics.',
      src: allSetSrc,
    },
    {
      zh: '简历一般包括个人信息，教育背景，工作经历等。',
      en:
        "A résumé generally includes a person's information, education background, work experience, etcetera.",
      src: allSetSrc,
    },
    {
      zh: '包括税，两张机票一共是五千。',
      en: 'Including taxes, two airplane tickets all together are $5,000.',
      src: allSetSrc,
    },
    {
      zh: '包括我在内，一共有十五个人参加这个会议。',
      en: 'Including myself, 15 people total participated in this meeting.',
      src: allSetSrc,
    },
    {
      zh: '包括奖金在内，这个月我拿了一万块钱工资。',
      en: 'Including bonuses, this month I received a salary of 1,000 RMB.',
      src: allSetSrc,
    },
    {
      zh: '包括母语在内，他一共会说四种语言。',
      en: 'Including my native language, I can speak a total of 4 languages.',
      src: allSetSrc,
    },
    {
      zh: '包括每个月的物业费，我们办公室的租金是两万。',
      en: "Including monthly property fees, our office's rent is $20,000.",
      src: allSetSrc,
    },
  ],
};
