/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGIZQJ2',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingAgainInTheFutureWithZai',
  name: 'Subj. + 再 + Verb Phrase',
  description:
    'While 又 (yòu) is used for "again" in the past, 再 (zài) is used for "again" in the future. That is, 再 is used when something has happened once and it will happen again.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(再)[^见]/)]);
  },
  examples: [
    {
      zh: '我明天再来。',
      en: "I'll come again tomorrow.",
      src: allSetSrc,
    },
    {
      zh: '请再说一遍。',
      en: 'Say it again, please.',
      src: allSetSrc,
    },
    {
      zh: '我想再看一遍。',
      en: 'I want to watch it again.',
      src: allSetSrc,
    },
    {
      zh: '你再试一下。',
      en: 'Try it again.',
      src: allSetSrc,
    },
    {
      zh: '你可以帮我再问一下吗？',
      en: 'Can you ask for me one more time?',
      src: allSetSrc,
    },
    {
      zh: '再吃一点。',
      en: 'Eat more.',
      src: allSetSrc,
    },
    {
      zh: '我们再找一个人吧。',
      en: "Let's find another person.",
      src: allSetSrc,
    },
    {
      zh: '我们再等他五分钟吧。',
      en: "Let's wait for him five more minutes.",
      src: allSetSrc,
    },
    {
      zh: '你再给我五十块。',
      en: 'Give me fifty more kuai.',
      src: allSetSrc,
    },
    {
      zh: '我们再给她一点时间。',
      en: "We'll give her a little more time.",
      src: allSetSrc,
    },
    {
      zh: '再找找。',
      en: 'Keep looking a little bit.',
      src: allSetSrc,
    },
    {
      zh: '再等等他吧。',
      en: 'Keep waiting for him for a little while.',
      src: allSetSrc,
    },
    {
      zh: '时间还早，再玩一会儿吧。',
      en: "It's still early. Let's keep playing for a while.",
      src: allSetSrc,
    },
    {
      zh: '现在才六点半，我想再睡一会儿。',
      en: "It's only 6:30. I want to sleep a little longer.",
      src: allSetSrc,
    },
    {
      zh: '你们想不想再休息一会儿？',
      en: 'Do you guys want to rest for a little longer?',
      src: allSetSrc,
    },
  ],
};
