/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG9B1E3',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingThroughWithTongguo',
  name: '通过 + Agent ，Subj. + ~',
  description: '',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(通过)/)]),
  examples: [
    {
      zh: '从我家走到这里需要通过两座桥。',
      en: 'To get here from my house, I have to cross two bridges.',
      src: allSetSrc,
    },
    {
      zh: '你往前走，通过一个红色的大门，然后左拐就看到了。',
      en: "Go straight ahead, go through a red door, turn left, and you'll see it.",
      src: allSetSrc,
    },
    {
      zh: '我通过了这次考试。',
      en: 'I passed this test.',
      src: allSetSrc,
    },
    {
      zh: '纽约大学通过了我的申请。',
      en: 'New York University went through my application.',
      src: allSetSrc,
    },
    {
      zh: '他没通过那家公司的面试。',
      en: "He didn't pass the interview by that company.",
      src: allSetSrc,
    },
    {
      zh: '我们是通过他的朋友找到他的。',
      en: 'We found him via his friends.',
      src: allSetSrc,
    },
    {
      zh: '通过这次调查，我们发现很多员工对新政策都不满意。',
      en:
        'Through this survey, we found many employees are not very satisfactory about the new policy.',
      src: allSetSrc,
    },
    {
      zh: '通过参加这个活动，大家互相都更了解了。',
      en: 'Through attending this activity, everyone knows more about each other.',
      src: allSetSrc,
    },
  ],
};
