/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG11DA8',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingAfterWithJingguo',
  name: '经过 + Event / Time，Subj. + Predicate',
  description:
    'The first way that 经过 is used as a verb is that it means "to pass by" or "to pass through." It is like saying "I went through downtown" or "I passed by the shop." As a preposition, 经过 means "to experience something" or "going through a time." It emphasizes the process of that experience. If it is talking about "going through a time," it is usually talking about the past. As a noun, 经过 refers to the process of something.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(经过)/)]),
  examples: [
    {
      zh: '我每天上班都会经过人民广场。',
      en: "I pass the People's Square every day on my way to work.",
      src: allSetSrc,
    },
    {
      zh: '你经过我家门口的时候叫我一下。',
      en: 'Call me when you pass by my door.',
      src: allSetSrc,
    },
    {
      zh: '她经过这个咖啡店的时候会想到他。',
      en: 'She thinks about him when she walks past this cafe.',
      src: allSetSrc,
    },
    {
      zh: '经过自己的努力，她考上了北京大学。',
      en: 'After all of her hard work, she was admitted into Peking University.',
      src: allSetSrc,
    },
    {
      zh: '经过两个月的准备，他顺利地通过了这次面试。',
      en: 'After two months of preparation, he successfully passed the job interview.',
      src: allSetSrc,
    },
    {
      zh: '经过调查，我们发现他跟这件事真的没有关系。',
      en: 'After investigating, we found out that he had nothing to do with this.',
      src: allSetSrc,
    },
    {
      zh: '经过这几年的发展，我老家发生了很大变化。',
      en: 'After the last few years of development, my hometown has changed a lot.',
      src: allSetSrc,
    },
    {
      zh: '经过一个月的培训，他对公司的业务已经比较熟悉了。',
      en: 'After going through a month of training, our staff is well prepared.',
      src: allSetSrc,
    },
    {
      zh: '请你跟我们说一下当时的经过。',
      en: 'Please tell us a little about that process.',
      src: allSetSrc,
    },
    {
      zh: '事情的真实经过谁都不知道。',
      en: 'No one knows the actual course of events.',
      src: allSetSrc,
    },
  ],
};
