/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGECD0E',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingDontNeedToWithBuyong',
  structures: ['Subj. + 不用 + [Verb Phrase]'],
  description:
    'In Chinese, "要" has many meanings, one of which is "need to". However, when you want to express  "don\'t need to", you actually use "不用", not "不要".',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(不用)/)]),
  examples: [
    {
      zh: '不用担心。',
      en: "You don't need to worry.",
      src: allSetSrc,
    },
    {
      zh: '不用你帮忙。',
      en: "You don't need to help.",
      src: allSetSrc,
    },
    {
      zh: '今天不用加班。',
      en: "We don't need to work overtime today.",
      src: allSetSrc,
    },
    {
      zh: '这件事不用跟他说。',
      en: "You don't need to tell him about this.",
      src: allSetSrc,
    },
    {
      zh: '告诉他明天不用来了。',
      en: "Tell him that he doesn't need to come tomorrow.",
      src: allSetSrc,
    },
    {
      zh: '大家不用给我买礼物。',
      en: "Guys, you don't need to buy me presents.",
      src: allSetSrc,
    },
    {
      zh: '今天人少，不用排队。',
      en: "There aren't many people today. We don't need to wait in line.",
      src: allSetSrc,
    },
    {
      zh: '五岁的孩子不用买票。',
      en: "Five-year-olds don't need to buy tickets.",
      src: allSetSrc,
    },
    {
      zh: '新员工不用参加这个会议。',
      en: "New employees don't need to attend this meeting.",
      src: allSetSrc,
    },
    {
      zh: '我们只去两天，你不用带这么多衣服。',
      en: "We are only going for two days. You don't need to take this much clothing.",
      src: allSetSrc,
    },
  ],
};
