/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG8KUHG',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingAlwaysWithConglai',
  name: 'Subj. + 从来 + 都 + Predicate',
  description:
    'Although perhaps more often used in the negative to mean "never," 从来 (cónglái) can be used with 都 (dōu) to mean "always" or "have always (done)."',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(从来都)/)]);
  },
  examples: [
    {
      zh: '我从来都一个人住，已经习惯了。',
      en: "I have always lived alone; I'm used to it already.",
      src: allSetSrc,
    },
    {
      zh: '她从来都这么自私。',
      en: "She's always been this selfish.",
      src: allSetSrc,
    },
    {
      zh: '我们下棋，他从来都是赢的。',
      en: 'He always wins when we play chess.',
      src: allSetSrc,
    },
    {
      zh: '他说话从来都很大声。',
      en: 'He always speaks very loudly.',
      src: allSetSrc,
    },
    {
      zh: '她找男朋友从来都是要长得帅的。',
      en: 'She always wants those good-looking guys when she looks for boyfriend.',
      src: allSetSrc,
    },
    {
      zh: '他工作从来都很努力。',
      en: 'He always works very hard.',
      src: allSetSrc,
    },
    {
      zh: '我的学生从来都这么有自信。',
      en: 'My students are always so confident.',
      src: allSetSrc,
    },
    {
      zh: '他的电影从来都是最受欢迎的。',
      en: 'His movies are always the most popular ones.',
      src: allSetSrc,
    },
    {
      zh: '成功从来都要靠自己努力。',
      en: "Success always depends on one's own efforts.",
      src: allSetSrc,
    },
  ],
};
