/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGB44F6',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingTheMoreTheMoreWithYueYue',
  structures: [
    'Subj. + 越 + Verb + 越 + Adj.',
    'Subj. +  越 + Verb 1 + 越 + Verb 2',
    'Subj. 1 + 越 + Verb，Subj. 2 + 越 + Adj.',
    'Subj. 1 + 越 + Verb 1，Subj. 2 + 越 + Verb 2',
    'Subj. + 越 + Verb + 越 + 想 + Verb',
  ],
  description:
    'More than just throwing anything you want after two 越s, there are a number of specific patterns you will notice if you want to go beyond using the simpler 越来越.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(越)[^越]+(越)/)]),
  examples: [
    {
      zh: '他越跑越快。',
      en: 'The more he runs, the faster he gets.',
      src: allSetSrc,
    },
    {
      zh: '雨越下越大。',
      en: 'The more it rains, the heavier the rain gets.',
      src: allSetSrc,
    },
    {
      zh: '我们越说越高兴。',
      en: 'The more we talk, the happier we are.',
      src: allSetSrc,
    },
    {
      zh: '她越想越生气。',
      en: 'The more she thinks about it, the angrier she gets.',
      src: allSetSrc,
    },
    {
      zh: '我越看越喜欢。',
      en: 'The more I look at it, the more I like it.',
      src: allSetSrc,
    },
    {
      zh: '她越说，我越生气。',
      en: 'The more she talks, the angrier I get.',
      src: allSetSrc,
    },
    {
      zh: '你们越看我，我越紧张。',
      en: 'The more you look at me, the more nervous I am.',
      src: allSetSrc,
    },
    {
      zh: '我越走，腿越痛。',
      en: 'The more I walk, the more my legs hurt.',
      src: allSetSrc,
    },
    {
      zh: '他越问，我越不想说。',
      en: 'The more he asks, the less I want to talk.',
      src: allSetSrc,
    },
    {
      zh: '你越逼他，他越讨厌你。',
      en: 'The more you push him, the more he hates you.',
      src: allSetSrc,
    },
    {
      zh: '我越看越想看。',
      en: 'The more I watch it, the more I want to watch.',
      src: allSetSrc,
    },
    {
      zh: '你会越吃越想吃。',
      en: 'The more you eat it, the more you will want to eat.',
      src: allSetSrc,
    },
    {
      zh: '这种花的味道让人越闻越想闻。',
      en: 'The more you smell this kind of flower, the more you want to smell it.',
      src: allSetSrc,
    },
    {
      zh: '不要给孩子喝这种饮料，他们会越喝越想喝。',
      en:
        "Don't give this kind of drink to kids. The more they drink it, the more they want to drink it.",
      src: allSetSrc,
    },
    {
      zh: '我吃了这个药以后总是想睡觉，而且越睡越想睡。',
      en:
        "I'm always so sleepy after taking this medicine. And also, the more I sleep, the more l want to sleep.",
      src: allSetSrc,
    },
  ],
};
