/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGKITRZ',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingEarlinessWithJiu',
  structures: [
    'Subj. + Time Word + 就 + Verb',
    'Subj. + Time  Word + 就 + Verb + Obj. + 了',
  ],
  description:
    'Just as 才 (cái) can express lateness, 就 (jiù) can be used to indicate that something happened earlier or sooner than expected.  It can also be used in the near future to indicate something will happen very soon. 早就 means "long ago," and is usually used to express a kind of impatience or surprise on the part of the speaker. It comes before the verb.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(早就)/),
      regexMatchLocs(
        sentence.text,
        /(?:[晚早马]上|[零一二三四五六七八九十百千万亿两0-9]点.?|[年月日号岁分钟快天午]|会儿)(就)/
      ),
    ]),
  examples: [
    {
      zh: '我马上就来。',
      en: "I'll be there in a second.",
      src: allSetSrc,
    },
    {
      zh: '他们一会儿就到。',
      en: 'They will be here in a few minutes.',
      src: allSetSrc,
    },
    {
      zh: '老板明天就回来。',
      en: 'The boss will be back tomorrow.',
      src: allSetSrc,
    },
    {
      zh: '我昨晚八点半就睡觉了。',
      en: 'I went to bed at half past eight last night.',
      src: allSetSrc,
    },
    {
      zh: '我们早上九点上课，可是他八点就来了。',
      en: 'We have class at nine in the morning, but he came at eight.',
      src: allSetSrc,
    },
    {
      zh: '爷爷每天五点就起床了。',
      en: "Grandpa gets up at five o'clock every day.",
      src: allSetSrc,
    },
    {
      zh: '她十八岁就大学毕业了。',
      en: 'She graduated from college when she was only 18 years old.',
      src: allSetSrc,
    },
    {
      zh: '我早就知道了！',
      en: 'I knew that long ago!',
      src: allSetSrc,
    },
    {
      zh: '她早就结婚了。',
      en: 'She got married long time ago.',
      src: allSetSrc,
    },
    {
      zh: '我们早就毕业了。',
      en: 'We graduated a long time ago!',
      src: allSetSrc,
    },
    {
      zh: '我早就跟你说过，他不是好人。',
      en: "I told you a long time ago that he's not a good guy.",
      src: allSetSrc,
    },
    {
      zh: '这家店早就关门了。',
      en: 'This shop closed a long time ago.',
      src: allSetSrc,
    },
  ],
};
