/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG8HVFN',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingExcessivelyWithTai',
  name: '太 + Adj. + 了',
  description:
    'In Chinese, the simplest structure for expressing "too" in the sense of "excessively" is by using the word 太 (tài). Don\'t forget to also add 了 (le) after the adjective to keep your Chinese sounding natural.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(太)[^了]+(了)/)]),
  examples: [
    {
      zh: '米饭太多了。',
      en: 'There is too much rice.',
      src: allSetSrc,
    },
    {
      zh: '现在太晚了。',
      en: "Now it's too late.",
      src: allSetSrc,
    },
    {
      zh: '老板太忙了。',
      en: 'The boss is too busy.',
      src: allSetSrc,
    },
    {
      zh: '老师太累了。',
      en: 'The teacher is too tired.',
      src: allSetSrc,
    },
    {
      zh: '这个厕所太脏了。',
      en: 'This restroom is too dirty.',
      src: allSetSrc,
    },
    {
      zh: '你太好了。',
      en: 'You are so great.',
      src: allSetSrc,
    },
    {
      zh: '他太帅了。',
      en: 'He is very handsome.',
      src: allSetSrc,
    },
    {
      zh: '这个女孩太漂亮了。',
      en: 'This girl is so pretty.',
      src: allSetSrc,
    },
    {
      zh: '小猫太可爱了！',
      en: 'The kitten is so cute!',
      src: allSetSrc,
    },
    {
      zh: '你的孩子太聪明了。',
      en: 'Your kids are wicked smart.',
      src: allSetSrc,
    },
  ],
};
