/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG8NM5E',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'expressingNeverWithConglai',
  name: 'Subj. + 从来 + 不 + [Verb Phrase]',
  description:
    "Although it can also work in the positive, 从来 (cónglái) is usually used when you want to express that you never do something (as a habit, or as a rule), or that you have never done something (it's not a part of your life experience). In either usage, 从来 (cónglái) may be shortened to just 从 (cóng) in casual speech.",
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(从来?不)/),
      regexMatchLocs(text, /(从来?没有?)[^过]+(过)/),
    ]);
  },
  examples: [
    {
      zh: '她从来不喝酒。',
      en: 'She never drinks.',
      src: allSetSrc,
    },
    {
      zh: '我女朋友从不给我打电话。',
      en: 'My girlfriend never calls me.',
      src: allSetSrc,
    },
    {
      zh: '这个人很奇怪，他从来不笑。',
      en: 'This person is very strange. He never laughs.',
      src: allSetSrc,
    },
    {
      zh: '你父母从来不打你吗？',
      en: 'Your parents never hit you?',
      src: allSetSrc,
    },
    {
      zh: '他从不关心别人。',
      en: 'He never cares about other people.',
      src: allSetSrc,
    },
    {
      zh: '你从来没有想过这个问题吗？',
      en: 'Have you never thought about this question?',
      src: allSetSrc,
    },
    {
      zh: '她从来没见过她妈妈。',
      en: 'She has never met her mother.',
      src: allSetSrc,
    },
    {
      zh: '我从没学过这个词。',
      en: 'I have never before studied this word.',
      src: allSetSrc,
    },
    {
      zh: '你们从来没有听说过这个地方吗？',
      en: 'Have you never heard about this place before?',
      src: allSetSrc,
    },
    {
      zh: '很多中国人从来没出过国。',
      en: 'A lot of Chinese people have never been abroad.',
      src: allSetSrc,
    },
  ],
};
