/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG84RE9',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'fenzhi',
  name: 'Denominator + 分之 + Numerator',
  description:
    '分之 (fēnzhī) is used to form a fraction in Chinese. When expressing a fraction, the denominator is always said before the numerator. This pattern is also the way percentages are expressed in Chinese.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /[零一二三四五六七八九十百千万亿两0-9](分之)[零一二三四五六七八九十百千万亿两0-9]/),
    ]),
  examples: [
    {
      zh: '蛋糕还有八分之一。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: '这桶水还有五分之三。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: '我的手机电量还有百分之三十。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: '押金要付百分之二十。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: '我们班有三分之一的同学是外国人。',
      en: 'One third of our classmates are foreign students.',
      src: allSetSrc,
    },
    {
      zh: '美国人口差不多是中国人口的四分之一。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: '我们学校四分之三的老师都是男老师。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: '我们的需求占整个市场需求的十分之三。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: '电动车的销量占新车销量的八分之五。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: 'Trump在这个州的支持率是百分之五十七点四。',
      en: '.',
      src: allSetSrc,
    },
    {
      zh: '过去二十年，大城市年轻人的离婚率增加了百分之八。',
      en: '.',
      src: allSetSrc,
    },
  ],
};
