/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGQJJYO',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'ganggang',
  name: 'Subj. + 刚 + Verb',
  description:
    'For events that happened in the immediate past, in English we use the word "just." For example, if you pass a turn you were supposed to make, you might say, "I just passed it!" In Chinese, "just" can be expressed with 刚 (gāng) or 刚刚 (gānggāng).',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(刚刚?)/)]),
  examples: [
    {
      zh: '我们刚知道。',
      en: 'We just found out.',
      src: allSetSrc,
    },
    {
      zh: '她们刚走。',
      en: 'They just left.',
      src: allSetSrc,
    },
    {
      zh: '老板刚刚到办公室。',
      en: 'The boss just arrived at the office.',
      src: allSetSrc,
    },
    {
      zh: '我老婆刚生完孩子。',
      en: 'My wife just finished giving birth to our baby.',
      src: allSetSrc,
    },
    {
      zh: '你刚刚下班吗？',
      en: 'Did you just get off work?',
      src: allSetSrc,
    },
    {
      zh: '我刚认识她十天。',
      en: 'I just met her ten days ago.',
      src: allSetSrc,
    },
    {
      zh: '他刚来中国两个月。',
      en: 'He just got to China two months ago.',
      src: allSetSrc,
    },
    {
      zh: '我弟弟刚工作半年。',
      en: 'My younger brother just started working half a year ago.',
      src: allSetSrc,
    },
    {
      zh: '她刚结婚三个月。',
      en: 'She just got married three months ago.',
      src: allSetSrc,
    },
    {
      zh: '我的车刚买两天，开的时候小心点。',
      en: 'I just bought the car two days ago. Be careful when you drive.',
      src: allSetSrc,
    },
  ],
};
