/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG49889',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'guanyu',
  name: '关于 + Obj.，Subj.  ⋯⋯',
  description:
    '关于 (guānyú) usually points to a range or scope, acting like the English word "about." It can be used in a few ways, often marking a topic of a statement, or modifying a noun.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(关于)/)]),
  examples: [
    {
      zh: '关于中国历史，我知道的不多。',
      en: "As for Chinese history, I don't know a lot.",
      src: allSetSrc,
    },
    {
      zh: '关于这次考试，我还有几个问题要问。',
      en: 'As for this exam, I still have a lot of questions that I need to ask.',
      src: allSetSrc,
    },
    {
      zh: '关于这个问题，你们还是问他吧。',
      en: "As for this problem, you'd better ask him.",
      src: allSetSrc,
    },
    {
      zh: '关于你的建议，老板还在考虑。',
      en: 'As for your suggestion, the boss is still thinking it over.',
      src: allSetSrc,
    },
    {
      zh: '关于那个调查结果，我们也不太清楚。',
      en: "As for the result of that research, we don't know much either.",
      src: allSetSrc,
    },
    {
      zh: '你有关于这次会议的PPT吗？',
      en: 'Do you have the Powerpoint for this meeting?',
      src: allSetSrc,
    },
    {
      zh: '这是一份关于中国市场的报告。',
      en: 'This is a report about the Chinese markets.',
      src: allSetSrc,
    },
    {
      zh: '关于这次旅行的计划还没做好。',
      en: "We haven't really figured out our plan for this trip yet.",
      src: allSetSrc,
    },
    {
      zh: '经理想了解更多关于新项目的情况。',
      en: 'The manager wants to know more about the new project.',
      src: allSetSrc,
    },
  ],
};
