/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG3ROPY',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'haoxiang',
  name: 'Subj. + 好像 + [Observation]',
  description: 'To express "seems," the word 好像 (hǎoxiàng) can be used.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(好像)/)]),
  examples: [
    {
      zh: '他们好像要结婚了。',
      en: 'They seem to be getting married.',
      src: allSetSrc,
    },
    {
      zh: '小猫好像饿了。',
      en: 'The small cat seems to be hungry.',
      src: allSetSrc,
    },
    {
      zh: '好像要下雨了。',
      en: "It seems like it's going to rain.",
      src: allSetSrc,
    },
    {
      zh: '你好像很生我的气。',
      en: 'You seem to be getting very upset with me.',
      src: allSetSrc,
    },
  ],
};
