/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG004ZK',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'indicatingANumberInExcess',
  name: 'Number + 多 + Measure word + (Noun)',
  description:
    'A number in excess of a certain amount is expressed by adding "多" (duō) to the end of a number. This is usually translated as "more than..." in English.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(多)/)]);
  },
  examples: [
    {
      zh: '他的妈妈已经五十多岁了。',
      en: 'His mother is already more than fifty years old.',
      src: allSetSrc,
    },
    {
      zh: '这个包三千多块钱？',
      en: 'This bag is more than three thousand kuai?',
      src: allSetSrc,
    },
    {
      zh: '我的毕业论文已经写了两百多页了！',
      en: 'My graduate dissertation is already more than two hundred pages!',
      src: allSetSrc,
    },
    {
      zh: '中国有五千多年的历史!',
      en: 'China has more than five thousand years of history!',
      src: allSetSrc,
    },
  ],
};
