/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGCPDSR',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'indicatingTheWholeWithQuan',
  name: '全 + Noun + 都  + Verb',
  description:
    'One of the uses of 全 (quán) is to indicate the entirety of something. It could be used for something like a whole household, an entire country, the whole world, etc.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(全)[^都]*(都)/)]),
  examples: [
    {
      zh: '我们全家都去旅游了。',
      en: 'The entire family went traveling.',
      src: allSetSrc,
    },
    {
      zh: '明天我全天都呆在家里。',
      en: 'I am going to stay home all day tomorrow.',
      src: allSetSrc,
    },
    {
      zh: '全公司的人都知道这件事了。',
      en: 'The whole company knew about this thing.',
      src: allSetSrc,
    },
    {
      zh: '打完球以后我全身都是汗。',
      en: 'My whole body sweat after playing the ball.',
      src: allSetSrc,
    },
    {
      zh: '全世界的人都知道Obama是谁，你不知道？',
      en: "The whole world knows who Obama is. Don't you know?",
      src: allSetSrc,
    },
    {
      zh: '大家全都到了。',
      en: 'Everybody has come.',
      src: allSetSrc,
    },
    {
      zh: '作业全都做完了吗？',
      en: "You've finished all your homework?",
      src: allSetSrc,
    },
    {
      zh: '我全都听懂了。',
      en: 'I heard and understood all.',
      src: allSetSrc,
    },
    {
      zh: '你全都拿走吧。',
      en: 'Take them all.',
      src: allSetSrc,
    },
    {
      zh: '他把咖啡全都喝了。',
      en: 'He drank up all the coffee.',
      src: allSetSrc,
    },
    {
      zh: '他们全都没去。',
      en: 'None of them went.',
      src: allSetSrc,
    },
    {
      zh: '这个周末我们全都不在家。',
      en: 'None of us will be home this weekend.',
      src: allSetSrc,
    },
    {
      zh: '他说的话全都不要相信。',
      en: "Don't believe anything he says.",
      src: allSetSrc,
    },
    {
      zh: '你们的员工全都不会说英语吗？',
      en: 'None of your employees can speak English?',
      src: allSetSrc,
    },
    {
      zh: '他们全都没学过汉语。',
      en: 'None of them have studied Chinese.',
      src: allSetSrc,
    },
    {
      zh: '我们的朋友没全都来。',
      en: 'Not all of our friends came.',
      src: allSetSrc,
    },
    {
      zh: '他的话你不能全都相信。',
      en: "You can't believe everything he says.",
      src: allSetSrc,
    },
    {
      zh: '中国菜我不全都喜欢。',
      en: "I don't like all Chinese food.",
      src: allSetSrc,
    },
    {
      zh: '这些菜我没全都吃完。',
      en: "I didn't eat all of the food.",
      src: allSetSrc,
    },
    {
      zh: '问题太多了，我没全都问他。',
      en: "I had too many questions for him. I didn't ask all of them.",
      src: allSetSrc,
    },
  ],
};
