/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGVRGW2',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'jiashiJiu',
  name: '假使 + Statement + 就 + Result',
  description:
    '"假使⋯⋯，就⋯⋯" (jiáshǐ..., jiù...) is another way to phrase "If..., then..." in Chinese, with this pattern being one of the most formal.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([regexMatchLocs(sentence.text, /(假使)[^就]+(就)?/)]),
  examples: [
    {
      zh: '假使明天下雨，我就不去上班了。',
      en: "If it rains tomorrow, then I'm not going to work.",
      src: allSetSrc,
    },
    {
      zh: '假使你同意，我们立马签合同。',
      en: 'If you agree, then we should sign the contract right away.',
      src: allSetSrc,
    },
    {
      zh: '假使我们能找到更多的赞助，我们就可以帮助更多的孩子。',
      en: 'If we find even more sponsors, then we can help even more children.',
      src: allSetSrc,
    },
  ],
};
