/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGVA70K',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'jihu',
  structures: [
    '几乎 + Subj. + 都 + Verb / Adj.',
    'Subj. + 几乎 + Predicate',
    'Subj. + 几乎 + 不 / 没 + Predicate',
  ],
  description:
    "几乎 (jīhū) means 'nearly', 'almost' or 'practically', and is used to emphasize that someone or something 'almost' meets a certain standard or is close to doing something.",
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([regexMatchLocs(sentence.text, /(几乎)[^都]+(都)?/)]),
  examples: [
    {
      zh: '几乎每个人都有手机。',
      en: 'Almost everyone has a cell phone.',
      src: allSetSrc,
    },
    {
      zh: '在我们公司，几乎每个人都会说英文。',
      en: 'In our company, almost everyone can speak English.',
      src: allSetSrc,
    },
    {
      zh: '在中国，几乎所有老外都会说“你好”。',
      en: 'In China, almost all of the foreigners can say "hello" in Chinese.',
      src: allSetSrc,
    },
    {
      zh: '几乎所有人都相信他。',
      en: 'Almost everyone believes what he said.',
      src: allSetSrc,
    },
    {
      zh: '几乎全世界的观众都喜欢这部电影。',
      en: 'Almost all the audience in the world like this movie.',
      src: allSetSrc,
    },
    {
      zh: '爸爸的头发几乎白了。',
      en: "Dad's hair is almost all white.",
      src: allSetSrc,
    },
    {
      zh: '这次旅行，他们几乎花了所有的钱。',
      en: 'They spent almost all the money on this trip.',
      src: allSetSrc,
    },
    {
      zh: '他一个人几乎吃了一整个蛋糕。',
      en: 'He almost ate this whole cake by himself.',
      src: allSetSrc,
    },
    {
      zh: '我老板几乎不喝酒。',
      en: "Almost all our family doesn't drink.",
      src: allSetSrc,
    },
    {
      zh: '老板这几个月几乎没好好休息过。',
      en: 'The boss barely has taken any good rest for the recent few months.',
      src: allSetSrc,
    },
  ],
};
