/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGG4BX9',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'jiran',
  name: '既然＋Fact, 那 / 就 / 那就＋Suggestion / Inference',
  description:
    '既然 (jìrán) means "since," and is often followed by 就 to mean "since...then...." It is used like this:',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(既然)[^那就]+(那|就|那就)?/)]);
  },
  examples: [
    {
      zh: '你既然不想说，那就别说了。',
      en: "Since you don't want to speak, just don't say it.",
      src: allSetSrc,
    },
    {
      zh: '既然你那么喜欢，那就买吧。',
      en: 'Since you like it so much, buy it then.',
      src: allSetSrc,
    },
    {
      zh: '她既然刚刚分手，那现在应该是单身吧。',
      en: 'Since she just had a breakup, she should be single now.',
      src: allSetSrc,
    },
    {
      zh: '既然你们是好朋友，那他肯定会帮你吧。',
      en: 'Since you guys are good friends, he will definitely help you.',
      src: allSetSrc,
    },
    {
      zh: '既然大家都不感兴趣，就换个话题吧。',
      en: "Since nobody is interested, let's change the topic.",
      src: allSetSrc,
    },
    {
      zh: '你既然不喜欢他，为什么还想跟他出去？',
      en: "Since you don't like him, why do you want to go out with him?",
      src: allSetSrc,
    },
    {
      zh: '既然你已经决定了，为什么现在后悔？',
      en: "Since you've made your decision, don't regret it then.",
      src: allSetSrc,
    },
    {
      zh: '既然他那么忙，你为什么还去打扰他？',
      en: "Since he's so busy, why would you bother him?",
      src: allSetSrc,
    },
    {
      zh: '既然已经分手了，为什么还要见面？',
      en: 'Since we broke up, why would we still see each other?',
      src: allSetSrc,
    },
    {
      zh: '既然你男朋友那么有钱，那他为什么不能大方一点？',
      en: "Since your boyfriend is so rich, why can't he be more generous?",
      src: allSetSrc,
    },
  ],
};
