/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGY21RK',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'jiushi',
  name: '就 + 是 + Noun',
  description:
    'As an adverb, 就 (jiù) can be placed before the predicate to add emphasis. It often has an intense or provocative feel to it, like how we sometimes say in English "it\'s just not right!," or other similar phrases. It often appears as 就是.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(就是)/),
      regexMatchLocs(sentence.text, /(就)[不要想喜]/),
    ]),
  examples: [
    {
      zh: '你就是个笨蛋！',
      en: "You're exactly a moron!",
      src: allSetSrc,
    },
    {
      zh: '他就是个骗子！',
      en: "He's exactly a liar!",
      src: allSetSrc,
    },
    {
      zh: '乔布斯就是我的偶像！',
      en: 'Jobs is exactly my idol!',
      src: allSetSrc,
    },
    {
      zh: '我就要去！',
      en: 'I just want to go!',
      src: allSetSrc,
    },
    {
      zh: '我就是喜欢他。',
      en: 'I just like him.',
      src: allSetSrc,
    },
    {
      zh: '他就想出国。',
      en: 'He just wants to go abroad.',
      src: allSetSrc,
    },
    {
      zh: '我问过很多次，他就是不说。',
      en: "I asked him many times. He just wouldn't tell.",
      src: allSetSrc,
    },
    {
      zh: '很多年轻人就喜欢打游戏。',
      en: 'A lot of young people just like to play video games.',
      src: allSetSrc,
    },
    {
      zh: '她就不听我的话。',
      en: "She just wouldn't listen to me.",
      src: allSetSrc,
    },
    {
      zh: '谁都知道抽烟对身体不好，可很多人就是不戒烟。',
      en:
        "Everyone knows that smoking is bad for your body but a lot of people just don't quit smoking.",
      src: allSetSrc,
    },
  ],
};
