/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGK213C',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'jiushi',
  name: '就是 + Adj.',
  description: '就是 (jiùshì) can be used to add many different types of emphasis.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(就是)/),
      regexMatchLocs(sentence.text, /(就)[不要]/),
    ]),
  examples: [
    {
      zh: '他就是聪明，考试总是第一名。',
      en: "He's just really smart. He's always gets the best grade on tests.",
      src: allSetSrc,
    },
    {
      zh: '我真的什么都没做，他就是对我有偏见。',
      en: "I really didn't do any of it. He's just prejudiced towards me.",
      src: allSetSrc,
    },
    {
      zh: '她就是漂亮，没什么别的优点。',
      en: "She's just pretty; she doesn't have other talents.",
      src: allSetSrc,
    },
    {
      zh: '我老公就是爱抽烟，他根本戒不了!',
      en: "My boss loves to smoke, he simply doesn't listen to the warnings.",
      src: allSetSrc,
    },
    {
      zh: '我就是不去，我一向都不爱去酒吧。',
      en: "I'm just not going to go. I've never liked going to bars.",
      src: allSetSrc,
    },
    {
      zh: '他就是不相信星座，你怎么跟他解释也没用。',
      en:
        "He just doesn't believe in astrology. No matter how you try to explain it to him, it won't work.",
      src: allSetSrc,
    },
  ],
};
