/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG9K0F8',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'kanqilai',
  name: 'Subj. + 看起来 + Adj.',
  description:
    'One of the most common ways to express "it looks like" is to use 看起来 (kànqǐlái). This is what we would use if we wanted to express something like, "she looks tired."',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(看起来)不?(像)?/)]),
  examples: [
    {
      zh: '这个看起来很漂亮。',
      en: 'This looks very pretty.',
      src: allSetSrc,
    },
    {
      zh: '他看起来很友好。',
      en: 'He looks friendly.',
      src: allSetSrc,
    },
    {
      zh: '这个蛋糕看起来很好吃。',
      en: 'This cake looks really tasty.',
      src: allSetSrc,
    },
    {
      zh: '你今天看起来很累。',
      en: 'You look really tired today.',
      src: allSetSrc,
    },
    {
      zh: '这家餐厅看起来不错。',
      en: 'This restaurant looks good.',
      src: allSetSrc,
    },
  ],
};
