/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGD4BA3',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'kongpa',
  structures: ['(Reason,) 恐怕 + Fact / Conclusion'],
  description:
    '恐怕 (kǒngpà) can be used to express "I\'m afraid that," or "I\'m concerned that," or even "I\'m worried that," followed by some sort of reason. It doesn\'t need to be something you\'re literally afraid of; it may be that you\'re just trying to soften the blow of some bad news, as in, "I\'m afraid that I\'m too busy washing my hair tomorrow night to come over and see the 2000 pictures of your trip to ComicCon."',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(恐怕)/)]),
  examples: [
    {
      zh: '明天我很忙，恐怕没有时间。',
      en: "I'm busy tomorrow, I'm afraid I don't have time.",
      src: allSetSrc,
    },
    {
      zh: '已经很晚了，恐怕他不会来了。',
      en: "It's already very late. I'm afraid he's not coming.",
      src: allSetSrc,
    },
    {
      zh: '这样做恐怕不行。',
      en: "I'm afraid it doesn't work this way.",
      src: allSetSrc,
    },
    {
      zh: '工作太多了，恐怕今天做不完。',
      en: "There's too much work. I'm afraid I can't finish it all today.",
      src: allSetSrc,
    },
    {
      zh: '饭太多了，恐怕我吃不完。',
      en: "Rice is too much. I'm afraid I can't eat it all.",
      src: allSetSrc,
    },
    {
      zh: '恐怕我今天没有时间做作业。',
      en: "I'm afraid today I don't have time to do homework.",
      src: allSetSrc,
    },
  ],
};
