/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG2KQZI',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'lingWai',
  structures: [
    '⋯⋯， 另外，⋯⋯',
    '另外 ＋ [Verb Phrase]',
    '另外 ＋ 一 + Measure Word + Noun',
    '另外 + [Plural Noun]',
  ],
  description:
    '另外 (lìng wài) can be used to express "in addition," often with 还 used in the following phrase.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(另外)/)]),
  examples: [
    {
      zh: '希望你不要再迟到了。另外，你应该穿得正式一点。',
      en:
        "I hope you won't be late again. In addition, you should also dress a little more formally.",
      src: allSetSrc,
    },
    {
      zh: '我刚才说的这些都很重要，不过大家另外补充的也很重要。',
      en:
        'What I just said is very important, but what everyone added is also very important.',
      src: allSetSrc,
    },
    {
      zh: '不好意思先生，这里是VIP室，要另外加钱才能用。',
      en:
        "I'm sorry sir, this is the VIP section. You will have to pay more in order to use it.",
      src: allSetSrc,
    },
    {
      zh: '我们这儿每天九点关门。九点以后，你还想学习的话，要另外找地方。',
      en:
        'We close at 9pm every day. You need to find another place if you still want to study after that.',
      src: allSetSrc,
    },
    {
      zh: '我有两个手机，一个是Lenovo，另外一个是iPhone。',
      en: 'I have two cell phones. One is Lenovo, and the other is iPhone.',
      src: allSetSrc,
    },
    {
      zh: '她有两套房子，一套自己住，另外一套租给了别人。',
      en: 'She has two houses. She lives in one and rents out the other one.',
      src: allSetSrc,
    },
    {
      zh: '我们可以早点去，另外几个人晚点到也没关系。',
      en:
        "We can go a  little bit earlier. It's OK that the other few people come a little bit late.",
      src: allSetSrc,
    },
    {
      zh: '这些书太重了，我想先带几本最近需要的，另外几本下次再拿。',
      en:
        "These books are too heavy. I want to take a few that I'll be needing recently. I can get the rest of them next time.",
      src: allSetSrc,
    },
  ],
};
