/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGL9KQM',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'measureWordsInQuantityQuestions',
  name: 'Subj. + Verb + 几 + Measure Word + Noun？',
  description:
    'Quantity questions are phrases for asking questions like "how much?" or "how many?"  You\'ll need to use the question word 几 (jǐ) with measure words for this.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(几)[^？]+(？)/),
      regexMatchLocs(sentence.text, /(多少)[^？]+(？)/),
    ]),
  examples: [
    {
      zh: '他有几个孩子？',
      en: 'How many kids does he have?',
      src: allSetSrc,
    },
    {
      zh: '你家有几个房间？',
      en: 'How many rooms are there in your house?',
      src: allSetSrc,
    },
    {
      zh: '他们在这里住几个星期？',
      en: 'How many weeks are they staying here?',
      src: allSetSrc,
    },
    {
      zh: '你带了几件衣服？',
      en: 'How many pieces of clothing have you brought?',
      src: allSetSrc,
    },
    {
      zh: '老板每天工作几个小时？',
      en: 'How many hours does the boss work every day?',
      src: allSetSrc,
    },
    {
      zh: '你去过多少个国家？',
      en: 'How many countries have you been to?',
      src: allSetSrc,
    },
    {
      zh: '你们班有多少个学生？',
      en: 'How many students are there in your class?',
      src: allSetSrc,
    },
    {
      zh: '你大学的时候看了多少本书？',
      en: 'How many books did you read when you were in college?',
      src: allSetSrc,
    },
    {
      zh: '他们昨天请了多少个朋友？',
      en: 'How many friends did they invite yesterday?',
      src: allSetSrc,
    },
    {
      zh: '上海有多少个外国公司？',
      en: 'How many foreign companies are there in Shanghai?',
      src: allSetSrc,
    },
  ],
};
