/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGI2KHC',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'meiBanfa',
  structures: ['Subj. + 没办法 + Verb + Obj.'],
  description:
    'If you are trying to express that something is impossible, you can use the phrase 没办法 (méi bànfǎ). 没办法 (méi bànfǎ) essentially means "there is no way," and whule it works just fine by itself, it can also come before verbs.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(没办法)/)]),
  examples: [
    {
      zh: '今天太忙了，中午没办法出去吃饭。',
      en: "It's too busy today. There's no way to go out for lunch.",
      src: allSetSrc,
    },
    {
      zh: '他没带手机，没办法给我打电话。',
      en: "He didn't bring his phone, so he has no way to give me a call.",
      src: allSetSrc,
    },
    {
      zh: '没有水，我们没办法洗衣服。',
      en: "There's no water. There's no way for us to wash clothes.",
      src: allSetSrc,
    },
    {
      zh: '这里太吵了，我没办法工作。',
      en: "It‘s too noisy here. I can't work.",
      src: allSetSrc,
    },
    {
      zh: '他不开门，所以她没办法进去。',
      en: "He didn't open the door, so she has no way to enter.",
      src: allSetSrc,
    },
    {
      zh: '你不会说中文，没办法在我们公司工作。',
      en: "You can't speak Chinese, so there is no way for you to work for our company.",
      src: allSetSrc,
    },
    {
      zh: '事情太多了，我今天没办法做完。',
      en: "There's too much to do. I have no way to finish today.",
      src: allSetSrc,
    },
    {
      zh: '老板不同意，我没办法帮你。',
      en: "The boss didn't agree, so I have no way to help you.",
      src: allSetSrc,
    },
    {
      zh: '这里没有wifi，我没办法上网。',
      en: 'There is no wifi here, so I have no way of going online.',
      src: allSetSrc,
    },
    {
      zh: '他很笨，我没办法跟他一起工作。',
      en: "He's really dumb. There is no way I can work with him.",
      src: allSetSrc,
    },
  ],
};
