/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGK904U',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'ordinalNumbersWithDi',
  name: '第 + Number',
  description:
    'We use ordinal numbers to express things like "number one" or "second," so mastering them in Chinese is important. Fortunately, they are also very easy to learn by just adding the prefix 第 (dì).',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(第)[零一二三四五六七八九十百千万亿两0-9]+/)]);
  },
  examples: [
    {
      zh: '我是第一个到公司的人。',
      en: "I'm the first person that came to the office.",
      src: allSetSrc,
    },
    {
      zh: '他要坐早上第一班地铁去上班。',
      en: 'He needs to take the first train in the morning to go to work.',
      src: allSetSrc,
    },
    {
      zh: '小李是她的第三个男朋友。',
      en: 'Little Li is her third boyfriend.',
      src: allSetSrc,
    },
    {
      zh: '我的第一个中文老师是美国人。',
      en: 'My first Chinese teacher was American.',
      src: allSetSrc,
    },
    {
      zh: '爸爸的第一个手机是NOKIA。',
      en: 'Dad‘s first cell phone was a  Nokia.',
      src: allSetSrc,
    },
    {
      zh: '你的第一个工作是什么？',
      en: 'What was your first job?',
      src: allSetSrc,
    },
    {
      zh: '到美国的第二个月，我找到了工作。',
      en: 'I found a job the second month I was in the USA.',
      src: allSetSrc,
    },
    {
      zh: '第二行第五个汉字怎么读？',
      en: 'How do you read the fifth character from the second line?',
      src: allSetSrc,
    },
    {
      zh: '这次考试，我是我们班第一。',
      en: 'On this test, I was first in our class.',
      src: allSetSrc,
    },
    {
      zh: '这次比赛，我们班第一，他们班第二。',
      en: 'In this contest, our class is the first, their class is the second.',
      src: allSetSrc,
    },
    {
      zh: '第一天，我们在宾馆里。',
      en: 'On the first day, we will be in the hotel.',
      src: allSetSrc,
    },
    {
      zh: '来上海以后的第二年，他开了这家公司。',
      en: 'He started this company his second year after coming to Shanghai.',
      src: allSetSrc,
    },
    {
      zh: '下个月的第一周老板要出差。',
      en: 'The boss needs to go on a business trip the first week of next month.',
      src: allSetSrc,
    },
    {
      zh: '这是我第一次去北京。',
      en: 'This is my first time going to Beijing.',
      src: allSetSrc,
    },
  ],
};
