/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGMJHZO',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'questionsWithNe',
  name: 'Topic + 呢 ？',
  description:
    'The particle 呢 (ne) can be used to ask reciprocal questions, also known as "bounce back" questions. 呢 (ne) can also be used to form simple questions asking "what about...?" or "how about...?"',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(呢？)/)]);
  },
  examples: [
    {
      zh: '这个很好，那个呢？',
      en: 'This one is good. What about that one?',
      src: allSetSrc,
    },
    {
      zh: '这个用中文怎么说？那个呢？',
      en: 'How do I say this in Chinese? And that?',
      src: allSetSrc,
    },
    {
      zh: '我在家，你呢？',
      en: "I'm at home. What about you?",
      src: allSetSrc,
    },
    {
      zh: '你爸爸是上海人，你妈妈呢？',
      en: 'Your father is Shanghainese. And your mom?',
      src: allSetSrc,
    },
    {
      zh: '你哥哥有工作，弟弟呢？',
      en: 'Your big brother has a job. What about your little brother?',
      src: allSetSrc,
    },
    {
      zh: '北京下雨了。上海呢？',
      en: "It's raining in Beijing. How about in Shanghai?",
      src: allSetSrc,
    },
    {
      zh: '我现在要出去。你呢？',
      en: "I'm going to go out now. How about you?",
      src: allSetSrc,
    },
    {
      zh: '我知道你会说中文。你老公呢？',
      en: 'I know you can speak Chinese. What about your husband?',
      src: allSetSrc,
    },
    {
      zh: '这个周末我想去酒吧。你们呢？',
      en: 'I want to go to a bar this weekend. What about you all?',
      src: allSetSrc,
    },
    {
      zh: '今天晚上没空？明天晚上呢？',
      en: "You don't have time tonight? What about tomorrow evening?",
      src: allSetSrc,
    },
    {
      zh: '钱呢？',
      en: "Where's the money?",
      src: allSetSrc,
    },
    {
      zh: '你妈妈呢？',
      en: "Where's your mom?",
      src: allSetSrc,
    },
    {
      zh: '我的手机呢？',
      en: "Where's my cell phone?",
      src: allSetSrc,
    },
  ],
};
