/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGP8DXU',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'renhe',
  structures: ['任何 + Noun'],
  description:
    '任何 (rènhé) is a modifier that means means "any," "whichever," or "whatsoever." It is also like the English phrases "any and all" or "no matter what."',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(任何)/)]),
  examples: [
    {
      zh: '这是我们俩的秘密，跟任何人都不要说。',
      en: "This is our secret. Don't tell it to anyone.",
      src: allSetSrc,
    },
    {
      zh: '我父母不让我参加任何校外的活动。',
      en: "My parents won't let me participate in any school activity.",
      src: allSetSrc,
    },
    {
      zh: '这么多年过去了，他还是没有任何变化。',
      en: "So many years have passed, and he hasn't changed a bit.",
      src: allSetSrc,
    },
    {
      zh: '这种情况在任何时候都不能发生。',
      en: "You can't let this kind of thing happen in any circumstance.",
      src: allSetSrc,
    },
    {
      zh: '我们老板人很好，你有任何想法都可以跟他说。',
      en:
        'Our boss is a very good person. Any thoughts you have you can discuss with him.',
      src: allSetSrc,
    },
    {
      zh: '我先走了，有任何需要给我打电话吧。',
      en: "I'm leaving now. Call me if you need anything.",
      src: allSetSrc,
    },
  ],
};
