/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGELOTT',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'reviewOptionsBa',
  name: '[Option 1] + 吧，[Evaluation]； [Option 2] + 吧， [Evaluation]',
  description:
    "When 吧 (ba) is used twice in a sentence, it is used to list two options that the speaker is debating. It gives the sentence an indecisive feel, as though the speaker doesn't know which one to choose. This construction often has a negative connotation, since the options usually are not ideal.",
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([regexMatchLocs(sentence.text, /(吧，)[^吧，]+(吧，)/)]),
  examples: [
    {
      zh: '去上海吧，太远；去北京吧，人太多。',
      en: 'Going to Shanghai is too far away, going to Beijing has too many people.',
      src: allSetSrc,
    },
    {
      zh: '冬天去吧，太冷；夏天去吧，太热。',
      en: 'Going in the winter is too cold, going in the summer is too hot.',
      src: allSetSrc,
    },
    {
      zh: '买房吧，没钱；不买房吧，没老婆。',
      en:
        "If you buy a house, you won't have money. If you don't buy a house you won't have a wife.",
      src: allSetSrc,
    },
    {
      zh: '学中文吧，太难；不学中文吧，找不到好工作。',
      en:
        "Studying Mandarin is too hard, but if you don't study Mandarin you cannot find a job.",
      src: allSetSrc,
    },
    {
      zh: '去学校工作吧，钱太少；去公司吧，太累。',
      en:
        'Working at the school, the pay is too little, but working at a company is too tiring.',
      src: allSetSrc,
    },
    {
      zh: '这件衣服，买吧，太贵；不买吧，又很喜欢。',
      en:
        "If I buy these clothes, they're too expensive, but if I don't buy them, I'll really want them.",
      src: allSetSrc,
    },
    {
      zh: '上班吧，很累；不上班吧，又无聊。',
      en: "Going to work? Too tiring. Not going to work? There's nothing to do.",
      src: allSetSrc,
    },
    {
      zh: '这件事情，你同意吧，你不高兴；不同意吧，别人不高兴。',
      en:
        "As for this matter, if you agree, you'll be unhappy, if you don't agree, other people will be unhappy.",
      src: allSetSrc,
    },
    {
      zh: '早点去吧，需要等；晚点吧，可能迟到。',
      en: "If we go early we'll have to wait, but if we go later, we might arrive late.",
      src: allSetSrc,
    },
    {
      zh: '在复习一点吧，太累了；去睡觉吧，怕明天考的不好。',
      en:
        "I should study more, but I'm too tired. However if I go to sleep now, I'm afraid I won't do well on the test tomorrow.",
      src: allSetSrc,
    },
  ],
};
