/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGN4VUU',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'ruguoDeHua',
  name: 'undefined',
  description:
    '"如果⋯⋯的话，⋯⋯" (rúguǒ... de huà, ...) is a pattern commonly used in Chinese to express "if." An easy way to remember the pattern\'s format is that in the full form, the condition is "sandwiched" between 如果 and 的话.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(如果)[^话]+(的话)?/),
      regexMatchLocs(sentence.text, /(如果)?[^话]+(的话)/),
    ]),
  examples: [
    {
      zh: '如果你有空的话，我们可以明天晚上看电影。',
      en: 'If you have time, we can go see a movie tomorrow night.',
      src: allSetSrc,
    },
    {
      zh: '如果没有你的帮助的话，他是不会得到这份工作的。',
      en: "If you didn't help him, he wouldn't get the job offer.",
      src: allSetSrc,
    },
    {
      zh: '如果你不来的话，老师会很失望。',
      en: "If you don't come, the teacher will be disappointed.",
      src: allSetSrc,
    },
  ],
};
