/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGN4VUU',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'ruguoDehua',
  structures: ['如果 ⋯⋯ 的话 ，(就) ⋯⋯', '⋯⋯ (的话) ，(就) ⋯⋯'],
  description:
    '"如果⋯⋯的话，⋯⋯" (rúguǒ... dehuà, ...) is a pattern commonly used in Chinese to express "if." An easy way to remember the pattern\'s format is that in the full form, the condition is "sandwiched" between 如果 and 的话. "就" is often optional.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /(如果)[^话]+(的话)?/),
      regexMatchLocs(sentence.text, /(如果)?[^话]+(的话)/),
    ]),
  examples: [
    {
      zh: '如果明天下雨的话，我们就不去了。',
      en: "If it rains tomorrow, we won't go.",
      src: allSetSrc,
    },
    {
      zh: '别点那么多菜。如果吃不完的话，就太浪费了。',
      en: "Don't order so much. It will be a big waste of food if we can't finish all.",
      src: allSetSrc,
    },
    {
      zh: '如果有人帮他的话，他就不会出事了。',
      en: "If someone had helped him, he would't have had this accident.",
      src: allSetSrc,
    },
    {
      zh: '如果你们不来的话，一定会后悔的。',
      en: "If you don't come, you'll definitely regret it.",
      src: allSetSrc,
    },
    {
      zh: '如果他还是不同意的话，你怎么办？',
      en: 'What will you do if he still disagree?',
      src: allSetSrc,
    },
    {
      zh: '你喜欢的话，就拿走吧。',
      en: 'Take it if you like it.',
      src: allSetSrc,
    },
    {
      zh: '见到他们的话，帮我问好。',
      en: 'If you meet them, tell them I say hello.',
      src: allSetSrc,
    },
    {
      zh: '不想去的话就别去了。',
      en: "Don't go if you don't feel like going.",
      src: allSetSrc,
    },
  ],
};
