/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGDIDAC',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'shenmeDe',
  name: 'Noun 1, Noun 2 (+ Noun 3) + 什么的',
  description:
    '什么的(shénme de) is an informal way to express "etc.," and is used to end a list of items when it is obvious to the listener what class of things the speaker is talking about. 什么的 can also be used after a single item if it is obvious enough what might follow.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(什么的)/)]),
  examples: [
    {
      zh: '我奶奶不吃肉，只吃蔬菜、豆腐什么的。',
      en: "My grandma doesn't eat meat. She only eats vegetables, tofu, and so on.",
      src: allSetSrc,
    },
    {
      zh: '养狗很麻烦，你要喂它，给他洗澡，跟它玩什么的。',
      en:
        'Having a dog gives you too much trouble. You need to feed it, give it a bath, play with it, and so on.',
      src: allSetSrc,
    },
    {
      zh: '数学、物理、化学什么的，我都不感兴趣。',
      en: "Math, physics, chemistry, and so on. I'm not interested in any of them.",
      src: allSetSrc,
    },
    {
      zh: '我喜欢实用的礼物，手表、衣服、书什么的。',
      en: 'I like practical presents, watch, clothes, books and so on.',
      src: allSetSrc,
    },
    {
      zh: '我们见面一般就是吃饭、聊天什么的。',
      en: 'When we meet, we just eat and talk, and so on.',
      src: allSetSrc,
    },
    {
      zh: '明天去野餐，我们要不要买一些水果，零食什么的。',
      en: 'We are going on picnic tomorrow. Shall we buy some fruits, snacks, and so on.',
      src: allSetSrc,
    },
    {
      zh: '跑步、游泳、篮球什么的，这些运动他都喜欢。',
      en: 'Running, swimming, basketball, and so on. He likes all these sports.',
      src: allSetSrc,
    },
    {
      zh: '长城、故宫什么的，都是北京很有名的景点。',
      en:
        "The Great Wall, Summer Palace, and so on. They're all very famous tourist attractions in Beijing.",
      src: allSetSrc,
    },
    {
      zh: '一个人住，洗衣服、做饭什么的都要自己做。',
      en:
        'When you live alone, you need to do things all by yourself, doing laundry, cooking, and so on.',
      src: allSetSrc,
    },
    {
      zh: '电视、洗衣机什么的，我爸爸都会修。',
      en: 'Television, washing machine, and so on. My father can fix many things.',
      src: allSetSrc,
    },
  ],
};
