/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGAQV6C',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'shenmeDou',
  name: 'Topic (+ Subj.) + 什么 + 都 / 也 + Verb / Adj.',
  description:
    '什么……都 (shénme... dōu) is a pattern often used to express "all" or "everything." Because it\'s not just one word, though, it can be a little tricky to get the hang of at first.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(什么)[^都也]*(都|也)/)]);
  },
  examples: [
    {
      zh: '我觉得这里的菜什么都好吃。',
      en: 'I think everything is delicious here.',
      src: allSetSrc,
    },
    {
      zh: '中国的历史爸爸什么都知道。',
      en: 'My dad knows everything about Chinese history.',
      src: allSetSrc,
    },
    {
      zh: '工作的事情老公什么都跟我说。',
      en: 'My husband tells me everything about work stuff.',
      src: allSetSrc,
    },
    {
      zh: '妈妈做的菜我什么都喜欢。',
      en: 'I like everything that mom cooks.',
      src: allSetSrc,
    },
    {
      zh: '我女朋友觉得外国的东西什么都好。',
      en: 'My  girlfriend thinks that all foreign things are good.',
      src: allSetSrc,
    },
    {
      zh: '我们什么果汁都喝。',
      en: 'We drink any kind of fruit juice.',
      src: allSetSrc,
    },
    {
      zh: '她什么衣服都是黑色的。',
      en: 'All of her clothes are black.',
      src: allSetSrc,
    },
    {
      zh: '妈妈做的什么菜都好吃。',
      en: 'All of the dishes mom makes are tasty.',
      src: allSetSrc,
    },
    {
      zh: '我男朋友什么运动都喜欢。',
      en: 'My boyfriend likes all kinds of sports.',
      src: allSetSrc,
    },
    {
      zh: '你不应该什么话都跟他说。',
      en: "You shouldn't tell him everything.",
      src: allSetSrc,
    },
    {
      zh: '生病以后，爸爸什么酒都不能喝了。',
      en: "After dad got sick, he can't drink any kind of alcohol.",
      src: allSetSrc,
    },
    {
      zh: '老板现在很生气，什么人也不见。',
      en: "The boss is very angry. He's doesn't want to see anybody.",
      src: allSetSrc,
    },
    {
      zh: '今天我不舒服，什么东西都没吃。',
      en: "Today I don't feel well, so I didn't eat anything.",
      src: allSetSrc,
    },
    {
      zh: '昨天开会的时候，她什么话也没说。',
      en: "She didn't say anything at yesterday's meeting.",
      src: allSetSrc,
    },
    {
      zh: '你在家里怎么什么事都不做？',
      en: "How  come you haven't done anything at home?",
      src: allSetSrc,
    },
  ],
};
