/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG8GSXY',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'usingYeAndDouTogether',
  structures: ['Subj. + 也 + 都 + Verb / Adj.'],
  description:
    'If you are trying to draw similarities amongst a group, you will want to pair two key words together. You will want to use 也 (yě) first followed by 都 (dōu) to express that a group of people have something in common.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(也都)/)]),
  examples: [
    {
      zh: '他们也都是法国人。',
      en: 'They are also all French people.',
      src: allSetSrc,
    },
    {
      zh: '我们也都喜欢喝啤酒。',
      en: 'We all like to drink beer too.',
      src: allSetSrc,
    },
    {
      zh: '你们也都是学生吗？',
      en: 'Are you all students too?',
      src: allSetSrc,
    },
    {
      zh: '我的三个孩子也都是男孩。',
      en: 'My three children are also all boys.',
      src: allSetSrc,
    },
    {
      zh: '我们办公室的女同事也都结婚了。',
      en: 'Our female colleagues are all married too.',
      src: allSetSrc,
    },
    {
      zh: '这个酒吧里也都是年轻人。',
      en: 'Everybody in this bar is also young.',
      src: allSetSrc,
    },
    {
      zh: '我们喜欢来这里，孩子们也都喜欢来这里。',
      en: 'We like to come here, all the kids also like to come here.',
      src: allSetSrc,
    },
    {
      zh: '老板经常加班，你们也都加班吗？',
      en: 'The boss constantly works overtime, do you all also work overtime?',
      src: allSetSrc,
    },
    {
      zh: '他们是你的朋友，他们也都是我的朋友。',
      en: 'They are your friends, they are all my friends too.',
      src: allSetSrc,
    },
    {
      zh: '北京的房子很贵，别的大城市的房子也都很贵。',
      en:
        'Apartments in Beijing are very expensive, in other big cities all apartments are also very expensive.',
      src: allSetSrc,
    },
    {
      zh: '这里的同事也都很好。',
      en: 'All the co-workers here are also really good.',
      src: allSetSrc,
    },
    {
      zh: '她的妹妹们也都很漂亮。',
      en: 'Her little sisters are also very beautiful.',
      src: allSetSrc,
    },
    {
      zh: '这家店的面包不错，别的点心也都很好吃。',
      en: "This store's bread is not bad, the other snacks are also very delicious.",
      src: allSetSrc,
    },
  ],
};
