/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGBZ578',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'usingLaiToConnectTwoVerbPhrases',
  name: '通过 / 用 + Agent + 来 + Verb Phrase',
  description:
    'The word 来 (lái) can be used to connect two verb phrases, relating the actions to each other. It can be translated as "in order to" or "so that" and it can help in explaining reasoning.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /((?:通过|用))[^来]+(来)/)]);
  },
  examples: [
    {
      zh: '用这种方法来赚钱，真丢人。',
      en: 'Using this method to earn money is shameful.',
      src: allSetSrc,
    },
    {
      zh: '用这个APP来学汉字更容易。',
      en: "It's easier to use this application to study Chinese characters.",
      src: allSetSrc,
    },
    {
      zh: '很多人都是通过这个网站来找工作的。',
      en: 'A lot of people hunt for a job through this website.',
      src: allSetSrc,
    },
    {
      zh: '我们可以通过打折来吸引顾客。',
      en: 'We can use a sale as a method to attract customers.',
      src: allSetSrc,
    },
    {
      zh: '他们是通过这个平台来推广产品的。',
      en: 'They promote their product through this platform.',
      src: allSetSrc,
    },
  ],
};
