/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGQGJXT',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'weile',
  name: '为了+ [Purpose]，Subject + Predicate',
  description:
    '为了 (wèile) is most often used to indicate the purpose of an action, or the person that will benefit from some act of kindness.  In the "purpose" sense, it corresponds pretty well to "in order to" or "for the purpose of" in English.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(为了)/)]);
  },
  examples: [
    {
      zh: '为了钱，他出卖了朋友。',
      en: 'He betrayed his friends for money.',
      src: allSetSrc,
    },
    {
      zh: '为了给他太太庆祝生日，他办了一个盛大的派对。',
      en: "He threw a grand party to celebrate his wife's birthday.",
      src: allSetSrc,
    },
    {
      zh: '为了有一个好的未来，我必须好好学习。',
      en: 'In order to have a good future, I have to study hard.',
      src: allSetSrc,
    },
    {
      zh: '为了让自己有更好的语言环境，我打算去中国留学一年。',
      en:
        'In order to have a better language-learning environment, I plan to go to study in China for 1 year.',
      src: allSetSrc,
    },
    {
      zh: '为了让孩子一生下来就是美国人，中国很多有钱人都在美国生孩子。',
      en:
        'In order to make their child an American citizen, a lot of  rich Chinese people stay in the United States during their pregnancy.',
      src: allSetSrc,
    },
    {
      zh: '我这么做是为了给你一个更好的未来。',
      en: 'The reason I did all this was to give you a better future.',
      src: allSetSrc,
    },
    {
      zh: '我离开中国是为了去美国结婚。',
      en: 'The reason I left China was to go to the United States to get married.',
      src: allSetSrc,
    },
    {
      zh: '他俩一直不要孩子是为了多点时间享受二人世界。',
      en:
        "The reason they don't want to have kids is so they can spend more time with each other.",
      src: allSetSrc,
    },
  ],
};
