/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGDFQP7',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yaobu',
  name: '要不 + Option A，要不 + Option B',
  description:
    '要不 (yàobù) can have a number of meanings, ranging from "either/or" to "how about."',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([regexMatchLocs(sentence.text, /(要不然?)[^吧]+(吧)?/)]),
  examples: [
    {
      zh: '要不你去，要不他去。',
      en: 'Either you go or he goes.',
      src: allSetSrc,
    },
    {
      zh: '你要不回家，要不陪我再玩一会儿。',
      en: 'You either go home or hang out with me a little more.',
      src: allSetSrc,
    },
    {
      zh: '你要不安静一点，要不就出去。',
      en: 'You can either be quiet or get out.',
      src: allSetSrc,
    },
    {
      zh: '一个人去没意思，要不我们一起去吧？',
      en: "It's no fun to go by myself. How about we go together?",
      src: allSetSrc,
    },
    {
      zh: '下雨了，要不明天再去吧。',
      en: "It's raining. How about we go tomorrow?",
      src: allSetSrc,
    },
    {
      zh: '家里停水了，要不今晚出去吃吧。',
      en: 'We have a blackout of water supply at home. How about we go eat out tonight?',
      src: allSetSrc,
    },
    {
      zh: '走路过去挺远的，要不我开车送你去吧。',
      en: "It's quite far away to walk there. How about I drive you there?",
      src: allSetSrc,
    },
    {
      zh: '要不我们去逛街吧，比在家看电视有意思。',
      en: "Let's go shopping. It's more fun than watching TV at home.",
      src: allSetSrc,
    },
    {
      zh: '打个车吧，要不会迟到的。',
      en: "You should take a taxi, otherwise you'll be late.",
      src: allSetSrc,
    },
    {
      zh: '快点做吧，要不又得加班了。',
      en: 'Do it faster, otherwise we are going to work late again.',
      src: allSetSrc,
    },
    {
      zh: '快点回家吧，要不你爸妈会担心的。',
      en: 'Hurry and go home, or your parents will start to worry.',
      src: allSetSrc,
    },
    {
      zh: '少放点辣椒，要不太辣了。',
      en: "Don't put so much chili pepper, otherwise it'll be so spicy.",
      src: allSetSrc,
    },
  ],
};
