/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG30A60',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yaome',
  name: 'Situation，要么 + Option B',
  description:
    'You can give a series of alternatives by using 要么 (yàome). The structure is pretty versatile, as you can put a wide variety of things after each 要么:',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(要么)[^要么]+(要么)?/)]);
  },
  examples: [
    {
      zh: '老板今天不在，要么你们明天再来吧。',
      en: "The boss isn't here today. How about if you all come back tomorrow?",
      src: allSetSrc,
    },
    {
      zh: '大家都觉得累得不行了，要么休息一会儿吧。',
      en: "Everyone is super tired. Why don't we rest for a while?",
      src: allSetSrc,
    },
    {
      zh: '最近这段时间大家都比较忙，要么过段时间再聚吧。',
      en:
        'Recently everyone has been pretty busy. How about we meet up after this busy period has passed?',
      src: allSetSrc,
    },
    {
      zh: '我周末还没安排，要么你们来我家一起做饭吧。',
      en:
        "I don't have plans for the weekend. How about you guys come to my place and we cook dinner together?",
      src: allSetSrc,
    },
    {
      zh: '我现在没那么多现金，要么先把我的身份证放在你这儿吧。',
      en:
        "I don't have that much cash right now. How about I leave my ID card with you for now?",
      src: allSetSrc,
    },
    {
      zh: '要么你去，要么他去。',
      en: 'Either you go, or he goes.',
      src: allSetSrc,
    },
    {
      zh: '要么现在就买，要么就别买。',
      en: "Either buy it now, or don't buy it.",
      src: allSetSrc,
    },
    {
      zh: '你要么快点找工作，要么准备考研，不能什么都不做。',
      en:
        "Either hurry up and find a job or apply for grad school, but you can't just do nothing.",
      src: allSetSrc,
    },
    {
      zh: '去年暑假，我每天要么去健身，要么去图书馆，特别无聊。',
      en:
        'Last summer vacation I either went to the gym or the library every day. It was so boring.',
      src: allSetSrc,
    },
    {
      zh: '你要么去看电视，要么出去玩，不要来打扰我工作。',
      en: 'Either go watch TV or go outside and play. Stop disturbing my work.',
      src: allSetSrc,
    },
  ],
};
