/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGITYYM',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yaoWoShuo',
  name: '要我说， Opinion',
  description:
    '“要我说” (yào wǒ shuō) is another, more colloquial way to say "in my opinion" or "the way I see it." It is generally used to express a person\'s perspective or opinion about a matter.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(要我说，)/)]),
  examples: [
    {
      zh: '要我说，这件事先不要告诉爸妈。',
      en: "The way I see it, this is something we shouldn't tell Mom and Dad.",
      src: allSetSrc,
    },
    {
      zh: '要我说，就去外面吃吧，不要在家做饭了。',
      en: 'I say we should just eat out instead of cooking at home.',
      src: allSetSrc,
    },
    {
      zh: '要我说，他就不应该跟老婆离婚。',
      en: "I think he shouldn't divorce his wife.",
      src: allSetSrc,
    },
    {
      zh: '要我说，带不带礼物都没关系，重要的是人要去。',
      en:
        "In my opinion, bringing gifts or not isn't what matters, the important thing is that people go.",
      src: allSetSrc,
    },
    {
      zh: '要我说，你们还是分手吧，他不适合你。',
      en: "I think you guys should break up. He's not right for you.",
      src: allSetSrc,
    },
  ],
};
