/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG2ZC5S',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yibianYibian',
  structures: ['Subj. + 一边 + Verb（，）+ 一边 + Verb'],
  description:
    'Multitasking is everywhere in the modern world (what else are you doing while you read this?), but you if can focus for just a minute, you can learn a way to express simultaneous tasks in Chinese! This can be done with 一边 (yībiān).',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([regexMatchLocs(sentence.text, /(一边)[^边]+(一边)/)]),
  examples: [
    {
      zh: '不要一边吃东西，一边说话。',
      en: "Don't speak while eating.",
      src: allSetSrc,
    },
    {
      zh: '我常常一边洗澡，一边唱歌。',
      en: 'I often sing songs while I take a shower.',
      src: allSetSrc,
    },
    {
      zh: '孩子喜欢一边吃饭，一边玩。',
      en: 'Children like to play while eating.',
      src: allSetSrc,
    },
    {
      zh: '你喜欢一边听音乐，一边做作业吗？',
      en: 'Do you like to listen to music while doing homework?',
      src: allSetSrc,
    },
    {
      zh: '我们一边走一边聊吧。',
      en: "Let's walk while we talk.",
      src: allSetSrc,
    },
    {
      zh: '请你一边读一边写。',
      en: 'Please write as you read.',
      src: allSetSrc,
    },
    {
      zh: '不要一边开车，一边打电话。',
      en: "Don't talk on the phone while you drive.",
      src: allSetSrc,
    },
    {
      zh: '老板喜欢一边抽烟，一边工作。',
      en: 'The boss likes to smoke while working.',
      src: allSetSrc,
    },
    {
      zh: '很多人都一边上班，一边玩手机。',
      en: 'Many people play with their cell phones while working.',
      src: allSetSrc,
    },
    {
      zh: '她常常一边做饭，一边带孩子。',
      en: 'She often looks after the baby while cooking food.',
      src: allSetSrc,
    },
  ],
};
