/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGXU2H4',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yibian',
  name: '[Action] +  以便 + [Outcome]',
  description:
    '以便 (yǐbiàn)  is a formal way to say "in order to" or "to facilitate," and is generally used to show that an outcome is the result of a particular action.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(以便)/)]),
  examples: [
    {
      zh: '我国提倡垃圾分类，以便回收再利用。',
      en:
        'My country advocates a garbage classification to help with reusing and recycling.',
      src: allSetSrc,
    },
    {
      zh: '老李买了一辆折叠式的自行车，以便携带。',
      en: 'Old Li bought a folding bike to make it easier to carry around.',
      src: allSetSrc,
    },
    {
      zh: '老师减慢了语速，以便学生能听懂。',
      en:
        'The teacher slowed down her talking speed so that the students could understand her.',
      src: allSetSrc,
    },
  ],
};
