/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGNEMXP',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yilai',
  structures: [
    'Time or Event + 以来',
    '自 / 从 / 自从 + Time or Event + 以来',
    'Time Interval + 来',
  ],
  description:
    'There are a few ways to express "ever since" in Chinese. In English, we would say something like "ever since I came to Shanghai, my Chinese has improved a lot." In this article, we will first take a look at using 以来 (yǐlái) to mean "ever since." We will also take a quick look at using "ever since" with 来 (lái), which is similar but used in a somewhat different way.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([
      regexMatchLocs(sentence.text, /((?:自|从|自从))[^以来]+(以来)/),
      regexMatchLocs(sentence.text, /(以来)/),
      regexMatchLocs(sentence.text, /[年月日号岁分钟秒天午](来)/),
    ]),
  examples: [
    {
      zh: '上大学以来，我一直没逃过课。',
      en: "Since I was in college, I haven't skipped a class.",
      src: allSetSrc,
    },
    {
      zh: '到上海以来，他的汉语水平提高了。',
      en: 'Ever since he came to Shanghai, his Chinese has been improving.',
      src: allSetSrc,
    },
    {
      zh: '住院以来，常常有朋友来医院看望她。',
      en:
        'Ever since she was in hospital, her friends have constantly come and visited her.',
      src: allSetSrc,
    },
    {
      zh: '自从我拿到驾照以来已经有五年了。',
      en: "I've had my license for five years.",
      src: allSetSrc,
    },
    {
      zh: '自从去年夏天以来，他一直没有回过家。',
      en: "He hasn't  returned home since last summer.",
      src: allSetSrc,
    },
    {
      zh: '自从退学以来，他一直在帮父母做农活。',
      en: "Since he left school,he's been helping her parents do farm work.",
      src: allSetSrc,
    },
    {
      zh: '自从1979年改革开放以来，中国人的生活水平得到了提高。',
      en: "Ever since the 1979 reform, the Chinese people's level of living has gone up.",
      src: allSetSrc,
    },
    {
      zh: '三个月来，我们去了很多地方旅游。',
      en: "Since three months ago, we've traveled to a lot of places.",
      src: allSetSrc,
    },
    {
      zh: '五年来，物价一直上涨。',
      en: 'Ever since five years ago, prices have been going up.',
      src: allSetSrc,
    },
    {
      zh: '我的同学几天来一直没有上课。',
      en: "My classmate hasn't come to class for a few days now.",
      src: allSetSrc,
    },
  ],
};
