/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGTDUJO',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yinweiSuoyi',
  name: 'Result, 因为 + Reason',
  description:
    'You will often come across 因为……所以…… (yīnwèi... suǒyǐ...) in both written and spoken Chinese. This pattern will give your Chinese a clear logical structure, and can help make you more persuasive.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(因为)[^所以]+(所以)/),
      regexMatchLocs(text, /(因为|所以)/),
    ]);
  },
  examples: [
    {
      zh: '他学得很快，因为他很聪明。',
      en: 'He learns fast because he is smart.',
      src: allSetSrc,
    },
    {
      zh: '我爱吃四川菜，因为很辣。',
      en: "I love eating Sichuan food because it's very spicy.",
      src: allSetSrc,
    },
    {
      zh: '我在学习中文，因为我想去中国。',
      en: 'I am studying Chinese because I want to go to China.',
      src: allSetSrc,
    },
    {
      zh: '我不喜欢她，因为她不友好。',
      en: "I don't like her because she is very unfriendly.",
      src: allSetSrc,
    },
    {
      zh: '今天我们很忙，因为有很多工作。',
      en: 'We are very busy today because we have lots of work.',
      src: allSetSrc,
    },
    {
      zh: '汉字太难了，所以我不想学。',
      en: "Chinese characters are too hard, so I don't want to study them.",
      src: allSetSrc,
    },
    {
      zh: '她很漂亮，所以很多男孩喜欢她。',
      en: 'She is beautiful, so a lot of boys like her.',
      src: allSetSrc,
    },
    {
      zh: '他找到工作了，所以很高兴。',
      en: "He found a job so he's happy.",
      src: allSetSrc,
    },
    {
      zh: '我太忙了，所以没有时间给你打电话。',
      en: "I was too busy, so I didn't have time to give you a call.",
      src: allSetSrc,
    },
    {
      zh: '我们公司有很多外国人，所以我们要说英文。',
      en: 'There are a lot of foreigners in our company, so we need to speak English.',
      src: allSetSrc,
    },
    {
      zh: '因为我有一个中国女朋友，所以我要学中文。',
      en: 'Since I have a Chinese girlfriend, I need to study Chinese.',
      src: allSetSrc,
    },
    {
      zh: '因为他生病了，所以没去上课。',
      en: "Since he was sick, he didn't go to class.",
      src: allSetSrc,
    },
    {
      zh: '因为我很累，所以要休息。',
      en: "I'm very tired, so I want to rest.",
      src: allSetSrc,
    },
    {
      zh: '因为太远了，所以我不想去。',
      en: "Since it's too far, I don't want to go.",
      src: allSetSrc,
    },
    {
      zh: '因为太忙，所以我们没有时间吃中饭。',
      en: 'We were too busy, so none of us had time to eat lunch.',
      src: allSetSrc,
    },
  ],
};
