/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGNVE15',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yiqi',
  name: 'Subj. + 一起 + Verb + Obj.',
  description:
    'If you want to express that you are doing something together with someone else, 一起 (yīqǐ) is your word!',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(一起)/)]),
  examples: [
    {
      zh: '我们一起吃晚饭吧。',
      en: "Let's eat dinner together.",
      src: allSetSrc,
    },
    {
      zh: '早上我和老公一起去上班。',
      en: 'In the morning, I go to work together with my husband.',
      src: allSetSrc,
    },
    {
      zh: '周末我们一起去看电影，好吗？',
      en: "Let's go to the movies this weekend, shall we?",
      src: allSetSrc,
    },
    {
      zh: '这两个公司一起做这个产品。',
      en: 'These two businesses made this product together.',
      src: allSetSrc,
    },
    {
      zh: '下班以后，你们一起来我家吧。',
      en: "After work, why don't you all come to my home together?",
      src: allSetSrc,
    },
    {
      zh: '下个月我和妈妈一起去旅行。',
      en: "Next month I'll go on a trip together with mom.",
      src: allSetSrc,
    },
    {
      zh: '你们有没有一起玩过这个游戏？',
      en: 'Have you all ever played this game together?',
      src: allSetSrc,
    },
    {
      zh: '他想和他太太一起学中文。',
      en: 'He wants to study Chinese together with his wife.',
      src: allSetSrc,
    },
    {
      zh: '结婚以后，你和父母会一起住吗？',
      en: 'Will you live together with your parents after you get married?',
      src: allSetSrc,
    },
    {
      zh: '今天晚上老板要和我们一起加班。',
      en: 'Tonight the boss is going to to work overtime together with us.',
      src: allSetSrc,
    },
  ],
};
