/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGWVZ0T',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yixie',
  name: '一些 + Noun',
  description:
    'In order to express "some" or "a few," you can use 一些 (yīxiē). To use it in this way, 一些 (yīxiē) is placed before the noun it modifies. 一些 (yīxiē) can modify the subject or the object.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(一些)/)]),
  examples: [
    {
      zh: '妈妈去超市买了一些水果。',
      en: 'Mom went to the supermarket and bought some fruit.',
      src: allSetSrc,
    },
    {
      zh: '上个周末他买了一些衣服。',
      en: 'He bought some clothes last weekend.',
      src: allSetSrc,
    },
    {
      zh: '我们很快会见到一些新同事。',
      en: "We're going to meet some new co-workers very soon.",
      src: allSetSrc,
    },
    {
      zh: '你饿不饿？这里有一些吃的。',
      en: 'Are you hungry or not? There is some food here.',
      src: allSetSrc,
    },
    {
      zh: '下课以后，学生们问了一些问题。',
      en: 'After class, the students asked some questions.',
      src: allSetSrc,
    },
    {
      zh: '给我一些时间，好吗？',
      en: 'Give me some time, OK?',
      src: allSetSrc,
    },
    {
      zh: '他给我带了一些书。',
      en: 'He brought me some books.',
      src: allSetSrc,
    },
    {
      zh: '你可以借我一些钱吗？',
      en: 'Can you lend me some money?',
      src: allSetSrc,
    },
    {
      zh: '你想在咖啡里放一些糖吗？',
      en: 'Do you want to put some sugar in your coffee?',
      src: allSetSrc,
    },
    {
      zh: '我在中国的时候，去过一些很漂亮的地方。',
      en: 'When I was in China, I went to some beautiful places.',
      src: allSetSrc,
    },
  ],
};
