/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGP000J',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yizhi',
  name: 'Subj. + 一直 + Predicate',
  description:
    '一直 (yīzhí) literally means "straight."  Used as an adverb, 一直 (yīzhí) can also be used to express that you have been doing something all along, have been continuously doing something since a certain time, or that something will continuously happen in the future.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(一直)/)]);
  },
  examples: [
    {
      zh: '我一直在学习中文。',
      en: "I've been studying Chinese all along.",
      src: allSetSrc,
    },
    {
      zh: '昨天晚上我一直在做作业。',
      en: 'Yesterday evening I was continuously doing homework.',
      src: allSetSrc,
    },
    {
      zh: '老板一直很忙。',
      en: 'The boss is always very busy.',
      src: allSetSrc,
    },
    {
      zh: '我一直很喜欢你。',
      en: "I've always liked you a lot.",
      src: allSetSrc,
    },
    {
      zh: '爸爸一直都不抽烟。',
      en: 'Dad has never smoked cigarettes.',
      src: allSetSrc,
    },
    {
      zh: '我男朋友一直在中国教英文。',
      en: 'My boyfriend has always been teaching English in China.',
      src: allSetSrc,
    },
    {
      zh: '18岁以后，他一直一个人住。',
      en: 'Since he was 18, he has always lived alone.',
      src: allSetSrc,
    },
    {
      zh: '你一直在这家公司工作吗？',
      en: 'Have you always worked in this company?',
      src: allSetSrc,
    },
    {
      zh: '你们一直住在一起吗？',
      en: 'Have you always been living together?',
      src: allSetSrc,
    },
    {
      zh: '北京的空气一直很不好。',
      en: 'The air in Beijing has been bad for a while.',
      src: allSetSrc,
    },
  ],
};
