/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGATDLX',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zaishuo',
  structures: ['Clause 1，再说 + Clause 2'],
  description:
    '"再说⋯⋯" (zàishuō...) is used in a similar way as "In addition" or "Moreover," in that it is adding on additional information or reasons to the topic at hand.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(再说)/)]),
  examples: [
    {
      zh: '我还不想结婚，因为年纪太小了。再说，也没有遇到合适的人。',
      en:
        "I don't want to get married yet because I'm too young. And besides, I haven't met the right one.",
      src: allSetSrc,
    },
    {
      zh: '现在太早了，我不想去，再说那个商店还没开门。',
      en: "It's too early now. I don't want to go. The store hasn't opened yet, anyway.",
      src: allSetSrc,
    },
    {
      zh: '我不想帮助他，因为他经常说谎，再说我也没钱。',
      en:
        "I don't want to help him because he lies a lot. Furthermore, I don't have any money.",
      src: allSetSrc,
    },
  ],
};
