/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGH2MNO',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zenme',
  name: 'Subj. + 怎么 + Verb + Obj.',
  description:
    '怎么 (zěnme) means "how" in Chinese, and it\'s not hard to use at all: just put it before a verb.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(怎么)(?:[^样]|$)/)]);
  },
  examples: [
    {
      zh: '你们怎么学中文？',
      en: 'How do you study Chinese?',
      src: allSetSrc,
    },
    {
      zh: '你怎么上班？坐地铁吗？',
      en: 'How do you get to work? By metro?',
      src: allSetSrc,
    },
    {
      zh: '你知道怎么去外滩吗？',
      en: 'Do you know how to get to the Bund?',
      src: allSetSrc,
    },
    {
      zh: '你怎么知道我喜欢旅行？',
      en: 'How did you know I like to travel?',
      src: allSetSrc,
    },
    {
      zh: '我不知道怎么跟女孩子说话。',
      en: "I don't know how to talk to girls.",
      src: allSetSrc,
    },
    {
      zh: '芒果怎么吃？',
      en: 'How do you eat mangos?',
      src: allSetSrc,
    },
    {
      zh: 'iPad怎么用？',
      en: 'How do you use an iPad?',
      src: allSetSrc,
    },
    {
      zh: '语法怎么学？',
      en: 'How do you study grammar?',
      src: allSetSrc,
    },
    {
      zh: '中国菜怎么做？',
      en: 'How do you cook Chinese food?',
      src: allSetSrc,
    },
    {
      zh: '"Apple"怎么说？',
      en: 'How do you say apple?',
      src: allSetSrc,
    },
  ],
};
