/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG1F4D1',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zheyang',
  name: 'Condition, 这样 + Result / Purpose',
  description:
    '这样 (zhèyàng) is used at the beginning of a phrase to express "this way" or "in this way."',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(这样)/)]),
  examples: [
    {
      zh: '我们还是坐地铁吧，这样更方便。',
      en: "We'd better take the metro. It's more convenient this way.",
      src: allSetSrc,
    },
    {
      zh: '你要多吃蔬菜，这样对身体更好。',
      en: "You should eat more vegetables. It's better for your body this way.",
      src: allSetSrc,
    },
    {
      zh: '你要多说，这样才能提高汉语口语。',
      en: 'You need to speak more. You can improve your spoken Chinese this way.',
      src: allSetSrc,
    },
    {
      zh: '你要让他自己做，只有这样他才能学会。',
      en: 'You should let him do it by himself. Only in this way can he learn.',
      src: allSetSrc,
    },
    {
      zh: '这样的话，你还怕什么呢？',
      en: 'What are you afraid of in this case?',
      src: allSetSrc,
    },
    {
      zh: '如果是这样的话，我觉得你们需要更多的帮助。',
      en: 'If this is the case, I think you need to get more help.',
      src: allSetSrc,
    },
    {
      zh: '如果不是这样的话，那你为什么生我的气？',
      en: 'If this is not the case, then why are you mad at me?',
      src: allSetSrc,
    },
    {
      zh: '如果不是这样的话，你还有什么更好的解释？',
      en: 'If this is not the case, do you have a better explanation?',
      src: allSetSrc,
    },
  ],
};
