/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGPY23Z',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zhileide',
  name: '像 + [Items] + 之类的',
  description:
    '之类的 (zhīlèide) can be translated as "and so on" or "and stuff like that." As in English, this grammar point is used to continue a list without explicitly mentioning further items within it.',
  sources: [allSetSrc],
  match: sentence =>
    mergeLocMatchGroups([regexMatchLocs(sentence.text, /(像)?[^类]+(之类的)/)]),
  examples: [
    {
      zh: '越来越多的人不吃快餐，像KFC之类的。',
      en: "More and more people don't eat fast food, like KFC and stuff like that.",
      src: allSetSrc,
    },
    {
      zh: '我喜欢呆在大城市，像上海、香港之类的。',
      en: 'I like to stay in big cities like Shanghai, Hong Kong, and places like that.',
      src: allSetSrc,
    },
    {
      zh: '他喜欢谈论漂亮的女明星，像章子怡、张柏芝之类的。',
      en:
        'He likes to talk about pretty actresses like Zhang Ziyi, Zhang Baizhi, and people like that.',
      src: allSetSrc,
    },
    {
      zh: '你喜欢看《西游记》之类的电影吗？',
      en: 'Do you like to watch movies like "Journey into the West"?',
      src: allSetSrc,
    },
    {
      zh: '一看就知道她很有钱，穿的都是Gucci、Chanel之类的衣服。',
      en:
        'You can tell she is rich as soon as you look at her. All of her clothes are brands like Gucci and Chanel.',
      src: allSetSrc,
    },
  ],
};
