/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGMT1M1',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zhiyi',
  structures: ['[Noun Phrase] + 之一'],
  description:
    'In order to express "one of the..." in Chinese, "之一" (zhī yī) can be used at the end of the sentence.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(之一)/)]),
  examples: [
    {
      zh: '她是我的好朋友之一。',
      en: 'She is one of my best friends.',
      src: allSetSrc,
    },
    {
      zh: '我觉得百事可乐是最好喝的饮料之一。',
      en: 'I think Pepsi is one of the best tasting drinks.',
      src: allSetSrc,
    },
    {
      zh: '纽约是世界上最国际化的城市之一。',
      en: 'New York is the one of the most international cities in the world.',
      src: allSetSrc,
    },
    {
      zh: '他是这个公司的创始人之一。',
      en: 'He is one of the founders of this company.',
      src: allSetSrc,
    },
    {
      zh: '成龙是最有名的动作明星之一。',
      en: 'Jackie Cheng is one of the most famous action movie stars.',
      src: allSetSrc,
    },
    {
      zh: '中国的空气污染是的老外经常抱怨的问题之一。',
      en:
        'in China, air pollution is one of the problems foreigners complain a lot about.',
      src: allSetSrc,
    },
    {
      zh: '中秋节是中国最重要的传统节日之一。',
      en: 'Mid-autumn Day is one of the most important traditional festivals in China.',
      src: allSetSrc,
    },
    {
      zh: '全球化是21世纪最大的特点之一。',
      en: 'Globalization is one of the major features of the 21st century.',
      src: allSetSrc,
    },
    {
      zh: '个性化是我们服务的主要特点之一。',
      en: 'Personalization is one of the major characteristics of our service.',
      src: allSetSrc,
    },
    {
      zh: '我选择这家公司的原因之一是我喜欢这里的工作环境。',
      en:
        'The reason why I choose this company is that I like the working environment here.',
      src: allSetSrc,
    },
  ],
};
