/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG700A5',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zhongyu',
  name: 'Subj. + 终于 + Verb Phrase + 了',
  description: '终于(zhōngyú) 表示经过很长时间的等待最后实现了愿望，通常都是说话人期待发生的事情，含喜悦、满意的感情色彩。',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(终于)[^了]+(了)/)]),
  examples: [
    {
      zh: '你终于到了！',
      en: 'You finally arrived!',
      src: allSetSrc,
    },
    {
      zh: '我们终于赢了！',
      en: 'We finally won!',
      src: allSetSrc,
    },
    {
      zh: '终于做完作业了！',
      en: 'I finally finished my homework!',
      src: allSetSrc,
    },
    {
      zh: '飞机终于起飞了！',
      en: 'The plane is finally taking off!',
      src: allSetSrc,
    },
    {
      zh: '饭终于做好了！我快饿死了。',
      en: "Dinner is finally ready! I'm starving.",
      src: allSetSrc,
    },
  ],
};
