/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups } = require('../lib/matching/utils');
const { regexMatchLocs } = require('../lib/matching/regexMatch');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGXJPJS',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zongshi',
  structures: ['Subj. + 总是 + Verb', '总是 + Adv. + Adj.'],
  description:
    'If you are trying to describe a daily routine, a habit, or just something that consistently happens, you can use the word 总是 (zǒngshì). 总是 (zǒngshì) means "always," and like other adverbs, comes before the verb in a sentence.',
  sources: [allSetSrc],
  match: sentence => mergeLocMatchGroups([regexMatchLocs(sentence.text, /(总是)/)]),
  examples: [
    {
      zh: '他总是迟到。',
      en: 'He is always late.',
      src: allSetSrc,
    },
    {
      zh: '我总是忘记这个词。',
      en: 'I always forget this word.',
      src: allSetSrc,
    },
    {
      zh: '他总是一个人吃饭。',
      en: 'He always eats alone.',
      src: allSetSrc,
    },
    {
      zh: '你男朋友总是说脏话。',
      en: 'Your boyfriend always uses foul language.',
      src: allSetSrc,
    },
    {
      zh: '我的学生总是问我很多有意思的问题。',
      en: 'My students always ask me lots of interesting questions.',
      src: allSetSrc,
    },
    {
      zh: '他总是很累。',
      en: 'He is always tired.',
      src: allSetSrc,
    },
    {
      zh: '你为什么总是很忙？',
      en: 'Why are you always very busy?',
      src: allSetSrc,
    },
    {
      zh: '你家总是很干净。',
      en: 'Your house is always very clean.',
      src: allSetSrc,
    },
    {
      zh: '孩子们总是非常开心。',
      en: 'The children are always very happy.',
      src: allSetSrc,
    },
    {
      zh: '我的学生总是特别努力。',
      en: 'My students are always very hard-working.',
      src: allSetSrc,
    },
  ],
};
