/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { regexMatchLocs } = require('../lib/matching/regexMatch');
const { mergeLocMatchGroups } = require('../lib/matching/utils');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG35CD7',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zuihao',
  name: 'Subj. + 最好 + [Verb Phrase]',
  description: '最好 can be used to express "had better"',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(最好)/),
      regexMatchLocs(text, /(最好(?:别|不要))/),
    ]);
  },
  examples: [
    {
      zh: '你最好先休息一下。',
      en: "You'd better take some rest first.",
      src: allSetSrc,
    },
    {
      zh: '你们最好给他打个电话问一下。',
      en: "You'd better call to ask him.",
      src: allSetSrc,
    },
    {
      zh: '那个地方不好找，我们最好查一下百度地图。',
      en: "It's not easy to find that place. We'd better search it on Baidu Map.",
      src: allSetSrc,
    },
    {
      zh: '外面挺冷的，最好多穿点。',
      en: "It's pretty cold outside. You'd better wear a little bit more.",
      src: allSetSrc,
    },
    {
      zh: '这个活动很重要，我们最好穿得正式一点。',
      en: "This is an important event. We'd better wear something more formal.",
      src: allSetSrc,
    },
    {
      zh: '最好别去。',
      en: "You'd better not go.",
      src: allSetSrc,
    },
    {
      zh: '最好不要这样说。',
      en: "You'd better not to say it like that.",
      src: allSetSrc,
    },
    {
      zh: '晚饭最好不要吃那么多。',
      en: "You'd better not so much for dinner.",
      src: allSetSrc,
    },
    {
      zh: '雨这么大，最好别出门。',
      en: "The rain is so heavy. You'd better not leave the house.",
      src: allSetSrc,
    },
    {
      zh: '这个问题是隐私，最好不要问。',
      en: "This question is privacy. We'd better not ask.",
      src: allSetSrc,
    },
  ],
};
