/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGEEA2D',
  name: 'AllSet Chinese Grammar Wiki',
};


module.exports = {
  id: 'expressingDoubleNegation',
  name: 'Subj.  + 不 + 是 + 不 / 没 +  [Verb Phrase]',
  description: '主要分两种，简单的是对能愿动词和谓语动词进行双重否定，较复杂的是对主语和谓语分别进行否定。',
  sources: [
    allSetSrc,
  ],
  match: (sentence) => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(不是(?:不|没))/),
      regexMatchLocs(text, /(不(?:会|能|可能)(?:不|没))/),
      regexMatchLocs(text, /(没有?)[^不没]+((?:不|没))/),
    ]);
  },
  examples: [
    {
      zh: '他不是不知道怎么做，只是不想做。',
      en: 'It\'s not that he doesn\'t know how to do it, he just doesn\'t want to do it.',
      src: allSetSrc,
    },
    {
      zh: '我不是没有想法，只是不想现在就说。',
      en: 'It\'s not that I don\'t have an opinion, I just don\'t want to say it right now.',
      src: allSetSrc,
    },
    {
      zh: '他是好学生，不会没做作业的。',
      en: 'He is a good student; he can\'t not do his homework.',
      src: allSetSrc,
    },
    {
      zh: '老板不会不同意的。',
      en: 'The boss can\'t disagree.',
      src: allSetSrc,
    },
    {
      zh: '买票不能不排队。',
      en: 'Buying a ticket doesn\'t mean you don\'t have to wait in line.',
      src: allSetSrc,
    },
    {
      zh: '他是你最好的朋友，不可能不来参加你的婚礼。',
      en: 'He is your best friend. There is no possibility he won\'t come take part in your wedding.',
      src: allSetSrc,
    },
    {
      zh: '有的人没带手机，但是不可能大家都没带手机。',
      en: 'Some people didn\'t bring their cell phones, but there is no possibility that everyone won\'t bring their cell phones.',
      src: allSetSrc,
    },
    {
      zh: '我知道你想减肥，但是不能不吃早饭。',
      en: 'I know you want to lose weight, but you can\'t not eat breakfast.',
      src: allSetSrc,
    },
    {
      zh: '这是团队活动，不能不参加。',
      en: 'This is a team activity. You can\'t not participate.',
      src: allSetSrc,
    },
    {
      zh: '没有一个人不讨厌他。',
      en: 'There is not one person who doesn\'t dislike him.',
      src: allSetSrc,
    },
    {
      zh: '没有谁不爱吃冰淇淋吧？',
      en: 'Is there no one who doesn\'t love eating ice cream?',
      src: allSetSrc,
    },
    {
      zh: '我们公司没有哪个员工不会说英语的。',
      en: 'Our company doesn\'t have employees who can\'t speak English.',
      src: allSetSrc,
    },
    {
      zh: '他的女朋友没有一个不漂亮的。',
      en: 'None of his girlfriends were not beautiful.',
      src: allSetSrc,
    },
    {
      zh: '我们班的学生没有一个不聪明的。',
      en: 'Our class doesn\'t have one student who isn\'t smart.',
      src: allSetSrc,
    },
  ],
};
