/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG3ZS9G',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'hekuang',
  name: 'Subj. + 连 + A + 都 + (不 / 没) + Verb， 何况 + B + 呢？',
  description:
    '何况 (hékuàng) can mean "let alone" or "all the more." It can be used in the following structure:',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(连?)[^都]+(都(?:(?:不|没)?))?[^何况]+(何况)[^呢]+(呢)?/),
    ]);
  },
  examples: [
    {
      zh: '我连一万块钱都有，何况一千呢？',
      en: "I have 10000 yuan, and you're saying I don't even have 1000?",
      src: allSetSrc,
    },
    {
      zh: '孩子连跑都会，何况走路呢？',
      en: 'The child can run, how could he not walk?',
      src: allSetSrc,
    },
    {
      zh: '你连那么难的试题都会，何况这么容易的呢？',
      en:
        'You can answer questions that hard, something like this should be easy, right?',
      src: allSetSrc,
    },
    {
      zh: '我连一千块钱都没有，何况一万呢？',
      en: "I don't even have 1000 yuan, let alone 10000.",
      src: allSetSrc,
    },
    {
      zh: '孩子连走路都不会，何况跑呢？',
      en: "The baby can't even walk, let alone run.",
      src: allSetSrc,
    },
    {
      zh: '你连这么简单的试题都不会，何况那么难的呢？',
      en:
        "You couldn't answer a question that easy, and you're kidding yourself you could answer one that hard?",
      src: allSetSrc,
    },
    {
      zh: '本地人都经常会迷路的，何况外地人！',
      en: 'Natives get lost all the time, so imagine the foreigners!',
      src: allSetSrc,
    },
    {
      zh: '这个地方本来就不好找，更何况你也是第一次来！',
      en: 'This place has always been hard to find, especially on your first time!',
      src: allSetSrc,
    },
  ],
};
