/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG8RW47',
  name: 'AllSet Chinese Grammar Wiki',
};


module.exports = {
  id: 'limitingScopeWithJiu',
  name: 'Subj. + 就 + 活动的对象或者范围 + Verb + Obj.',
  description: '"Limiting scope" means saying, "what I\'m about to say applies to just this. You proceed the "this" with 就 (jiù) in this pattern.',
  sources: [
    allSetSrc,
  ],
  match: (sentence) => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(就活动的对象或者范围)/),
      regexMatchLocs(text, /(就)[^来说而言]+((?:(?:来说|而言)?))/),
    ]);
  },
  examples: [
    {
      zh: '大家就中国互联网的发展发表了各自的看法。',
      en: '',
      src: allSetSrc,
    },
    {
      zh: '中国主席就中国最近的经济改革做了发言。',
      en: '',
      src: allSetSrc,
    },
    {
      zh: '来自各国的教育学者们就什么是最好的教育方法进行了激烈的讨论。',
      en: '',
      src: allSetSrc,
    },
    {
      zh: '就中国的独生子女政策而言，专家各有各的看法。',
      en: 'As for China\'s One Child Policy, every expert has their own opinion.',
      src: allSetSrc,
    },
    {
      zh: '就文化大革命而言，大部分的人都认为那是一场灾难。',
      en: 'As for the Cultural Revolution, a large part of the people think it was a disaster.',
      src: allSetSrc,
    },
    {
      zh: '就这些事情来说，他没有错。',
      en: 'In regards to these sorts of things, he didn\'t do anything wrong.',
      src: allSetSrc,
    },
  ],
};
