/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGAY164',
  name: 'AllSet Chinese Grammar Wiki',
};


module.exports = {
  id: 'moderatingPositiveAdjectivesWithHai',
  name: 'Subj. + 还 + 好 / 可以 / 行 / 不错',
  description: 'Whenever you want to imply that something is "good," but also kind of "meh," you can use 还 (hái) in front of the "good" adjective.',
  sources: [
    allSetSrc,
  ],
  match: (sentence) => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(还(?:好|可以|行|不错))/),
    ]);
  },
  examples: [
    {
      zh: '我还好。',
      en: 'I\'m OK.',
      src: allSetSrc,
    },
    {
      zh: '爸爸做的菜还可以。',
      en: 'The food that dad cooks is OK.',
      src: allSetSrc,
    },
    {
      zh: '我们老板还不错。',
      en: 'Our boss is not too bad.',
      src: allSetSrc,
    },
    {
      zh: '这家店还行，不太贵。',
      en: 'This shop is OK. It\'s not too expensive.',
      src: allSetSrc,
    },
    {
      zh: '我男朋友的工资还可以。',
      en: 'My boyfriend\'s salary is OK.',
      src: allSetSrc,
    },
    {
      zh: '新的办公室还不错。',
      en: 'The new office is OK.',
      src: allSetSrc,
    },
    {
      zh: '我觉得这里的菜还可以，没有那么难吃。',
      en: 'I think the food here is OK, it is not too bad-tasting.',
      src: allSetSrc,
    },
    {
      zh: '这个牌子还不错，很多年轻人喜欢。',
      en: 'This brand is not too bad. Many young people like it.',
      src: allSetSrc,
    },
    {
      zh: '房子还可以，但是有点贵。',
      en: 'The apartment is not too bad, but it is a bit expensive.',
      src: allSetSrc,
    },
  ],
};
