/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/matchingHelpers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGN6BBU',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'bigToSmall',
  name: '(Date and/or time of day +) x 点',
  description:
    'Time in Chinese, just like in English, is expressed by stating the hour first, and then the minute (big to small).',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /([零一二三四五六七八九十百千万亿两0-9]+点)/),
      regexMatchLocs(text, /([零一二三四五六七八九十百千万亿两0-9]+点半)/),
    ]);
  },
  examples: [
    {
      zh: '九点',
      en: "9 o'clock",
      src: allSetSrc,
    },
    {
      zh: '上午七点',
      en: "7 o'clock a.m.",
      src: allSetSrc,
    },
    {
      zh: '下午四点',
      en: "4 o'clock p.m.",
      src: allSetSrc,
    },
    {
      zh: '中午十二点',
      en: "12 o'clock noon",
      src: allSetSrc,
    },
    {
      zh: '明天晚上七点',
      en: "7 o'clock p.m. tomorrow evening",
      src: allSetSrc,
    },
    {
      zh: '9月9号早上六点',
      en: "September 9th, 6 o'clock a.m.",
      src: allSetSrc,
    },
    {
      zh: '星期三上午九点',
      en: "Wednesday at 9 o'clock a.m.",
      src: allSetSrc,
    },
    {
      zh: '五点半',
      en: '5:30',
      src: allSetSrc,
    },
    {
      zh: '下午两点半',
      en: '2:30 p.m.',
      src: allSetSrc,
    },
    {
      zh: '星期天上午十点半',
      en: 'Sunday at 10:30 a.m.',
      src: allSetSrc,
    },
    {
      zh: '昨天晚上七点半',
      en: '7:30 yesterday evening',
      src: allSetSrc,
    },
    {
      zh: '今天下午四点半',
      en: '4:30 p.m. this afternoon.',
      src: allSetSrc,
    },
  ],
};
