/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGOWBSL',
  name: 'AllSet Chinese Grammar Wiki',
};


module.exports = {
  id: 'referringToAllUsingSuoyou',
  name: '所有的 + Noun + 都 + Verb / Adj.',
  description: 'In this grammar structure, we learn about a way to say "all" that is, well, a bit more epic. Sort of like how we might say "all the king\'s men" or "all the money in the world."',
  sources: [
    allSetSrc,
  ],
  match: (sentence) => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(所有的?)[^都]+(都)?/),
    ]);
  },
  examples: [
    {
      zh: '我爱吃所有的中国菜。',
      en: 'I love eating all the Chinese food.',
      src: allSetSrc,
    },
    {
      zh: '他记得所有人的生日。',
      en: 'He remembers everyone\'s birthday.',
      src: allSetSrc,
    },
    {
      zh: '这里所有的女孩都没上过学。',
      en: 'All of the girls here have never gone to school.',
      src: allSetSrc,
    },
    {
      zh: '不是所有的美国人都爱喝咖啡。',
      en: 'Not all the Americans like drinking coffee.',
      src: allSetSrc,
    },
    {
      zh: '我们部门所有的员工都会说英文。',
      en: 'All the employees from our department can speak English.',
      src: allSetSrc,
    },
    {
      zh: '你们公司所有的经理都是男的吗？',
      en: 'All the managers in your company are male?',
      src: allSetSrc,
    },
    {
      zh: '我看过所有的迪斯尼动画片。',
      en: 'I\'ve seen all the Disney movies.',
      src: allSetSrc,
    },
    {
      zh: '他找了所有的朋友，但是没有人帮他。',
      en: 'He went to all his friends, but nobody helped him.',
      src: allSetSrc,
    },
    {
      zh: '钱不可能解决所有的问题。',
      en: 'Money can\'t solve all the problems.',
      src: allSetSrc,
    },
    {
      zh: '老板让所有的员工都去参加这个会。',
      en: 'Boss asked all the employees to attend this meeting.',
      src: allSetSrc,
    },
  ],
};
