/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG7AUNJ',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'usingZheWhenVerbingAway',
  name: 'Verb + 着 + Verb + 着 + 就 + Comment + 了',
  description:
    'A repeated verb followed by the particle 着 (zhe) is used to show that an action has be repeated for a period of time, and as a result a new situation has arisen which the speaker wishes to comment on.',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(着)[^着就]+(着)[^就]*(就)[^了]+(了)/)]);
  },
  examples: [
    {
      zh: '说着说着我就发现自己也糊涂了。',
      en: 'I was talking and talking, and then I confused myself.',
      src: allSetSrc,
    },
    {
      zh: '我今天一直都在看语法的书，看着看着，就睡着了。',
      en:
        'Today, I was constantly studying the grammar books. As I was studying, I fell asleep.',
      src: allSetSrc,
    },
    {
      zh: '我在北京的胡同里走着走着就走丢了。',
      en: "As I was walking in one of Beijing's back roads, I got lost.",
      src: allSetSrc,
    },
  ],
};
