/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGOB1BF',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'xingkui',
  name: '幸亏 / 幸好 + [Lucky Incident]',
  description:
    '幸亏 (xìngkuī), 幸好 (xìnghǎo), and 还好 (háihǎo) mean "fortunately" or "luckily." They can be used to express that something has happened by chance, and has thereby enabled you to avoid some difficulty or bad luck. It is often followed with 不然 (which precedes the bad thing that could have happened).',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /((?:幸亏|幸好|还好))[^然]+(不然)?/)]);
  },
  examples: [
    {
      zh: '幸亏我们走得早，不然就迟到了。',
      en: 'Luckily, we left early, otherwise we could have been late.',
      src: allSetSrc,
    },
    {
      zh: '幸好我妈没看到，不然她肯定要生气。',
      en:
        "It's a good thing that my mother didn't see it, otherwise she would definitely be mad.",
      src: allSetSrc,
    },
    {
      zh: '幸亏你在，不然我不知道该找谁。',
      en: "Fortunately you're here, otherwise I don't know who I could turn to.",
      src: allSetSrc,
    },
    {
      zh: '幸好他们都走了，不然我要疯了。',
      en: 'Luckily, they all left, otherwise I could be driven crazy.',
      src: allSetSrc,
    },
    {
      zh: '幸好今天带伞了，不然要淋湿了。',
      en:
        "It's a good thing I brought the umbrella. Otherwise, I would have gotten soaked.",
      src: allSetSrc,
    },
    {
      zh: '还好我没听他的话，不然我就输了。',
      en:
        "It's a good thing I didn't listen to him, otherwise I would have lost the game.",
      src: allSetSrc,
    },
    {
      zh: '还好我保存了，不然文件都丢了。',
      en: 'Luckily I saved it, otherwise I would have lost all of the documents.',
      src: allSetSrc,
    },
    {
      zh: '还好我买得少，不然都浪费了。',
      en: "Luckily I didn't buy a lot, otherwise the food would be all wasted.",
      src: allSetSrc,
    },
    {
      zh: '还好老板不知道，不然你肯定被炒鱿鱼。',
      en:
        "Luckily the boss doesn't know about it, otherwise you will definitely get fired.",
      src: allSetSrc,
    },
    {
      zh: '还好你提醒我，不然我肯定忘了。',
      en: 'Luckily, you reminded me, otherwise I would have definitely forgotten.',
      src: allSetSrc,
    },
  ],
};
