/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/matchingHelpers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGLNKZR',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yihou',
  name: 'Subj. + Verb + 以后／的时候， Comment',
  description:
    'When talking about when something happens, "以后" (yǐhòu) and "的时候" (de shíhou) are often used. They can both be translated as "when," but their meanings are different, so they can\'t be used in situations you might expect them to be used in. Take a look at this article if you want to figure it out!',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /(以后|的时候)/)]);
  },
  examples: [
    {
      zh: '下飞机以后给我打电话。',
      en: 'Give me a call after you get off the plane.',
      src: allSetSrc,
    },
    {
      zh: '有了孩子以后他更没时间出来玩了。',
      en: 'After having a child, he has even less time to come out and have fun.',
      src: allSetSrc,
    },
    {
      zh: '下班以后我们一起去吃饭。',
      en: "After work, we're going to go eat together.",
      src: allSetSrc,
    },
    {
      zh: '来中国以后我才发现中国菜那么好吃。',
      en: 'Only when I got to China did I realize how tasty Chinese food is.',
      src: allSetSrc,
    },
    {
      zh: '毕业以后我打算去上海工作。',
      en: 'I plan to find a job in Shanghai after I graduate.',
      src: allSetSrc,
    },
    {
      zh: '结婚以后你还会工作吗？',
      en: 'Are you still working after you get married?',
      src: allSetSrc,
    },
    {
      zh: '吃饭的时候看电视容易长胖。',
      en: 'Watching TV while you eat can make you fat easily.',
      src: allSetSrc,
    },
    {
      zh: '公司规定工作的时候不能用QQ聊天。',
      en: "Company rules say that you can't chat on QQ when you're at work.",
      src: allSetSrc,
    },
    {
      zh: '无聊的时候可以做些什么？',
      en: "What can you do when you're bored?",
      src: allSetSrc,
    },
    {
      zh: '打篮球的时候会出很多汗。',
      en: 'You sweat a lot when you play basketball.',
      src: allSetSrc,
    },
    {
      zh: '看电影的时候你喜欢吃东西吗？',
      en: 'Do you like to eat while you watch a movie?',
      src: allSetSrc,
    },
    {
      zh: '下班的时候我给你打电话。',
      en: 'When you get off work, call me.',
      src: allSetSrc,
    },
    {
      zh: '下班以后我给你打电话。',
      en: 'When you get off work, call me.',
      src: allSetSrc,
    },
    {
      zh: '雨停了的时候，我们就去公园玩。',
      en: "When it stops raining, we'll go play in the park.",
      src: allSetSrc,
    },
    {
      zh: '雨停了以后，我们就去公园玩。',
      en: "When it stops raining, we'll go play in the park.",
      src: allSetSrc,
    },
    {
      zh: '商店关门的时候，你再来找我。',
      en: 'Come to find me when the shop is closed.',
      src: allSetSrc,
    },
    {
      zh: '商店关门了以后，你再来找我。',
      en: 'Come to find me when the shop is closed.',
      src: allSetSrc,
    },
  ],
};
