/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASG7UE4H',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'yuelaiyue',
  name: 'Subj. + 越来越 + Adj. + 了',
  description:
    '越来越 (yuèláiyuè) is used frequently in Chinese to express that some quality or state is increasing with time, or in tune with another factor.  There are two forms of this pattern, the "simple" one (using 来), and the more complex one (which uses two different adjectives/verbs).',
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([
      regexMatchLocs(text, /(越来越)[^了]+(了)/),
      regexMatchLocs(text, /(越来越)[^了]+(了)/),
    ]);
  },
  examples: [
    {
      zh: '天气越来越冷了。',
      en: 'The weather is getting colder and colder.',
      src: allSetSrc,
    },
    {
      zh: '你女儿越来越漂亮了。',
      en: 'Your daughter is getting more and more beautiful.',
      src: allSetSrc,
    },
    {
      zh: '你做的菜越来越好吃了。',
      en: 'The food that you cook is more and more delicious.',
      src: allSetSrc,
    },
    {
      zh: '汽油越来越贵了。',
      en: 'Gasoline is getting more and more expensive.',
      src: allSetSrc,
    },
    {
      zh: '上海的房价越来越高了。',
      en: 'The housing price in Shanghai is getting higher and higher.',
      src: allSetSrc,
    },
    {
      zh: '来中国以后，他越来越喜欢吃辣了。',
      en: 'After he came to China, he likes eating spicy food more and more.',
      src: allSetSrc,
    },
    {
      zh: '我越来越想家了。',
      en: "I'm getting more and more homesick.",
      src: allSetSrc,
    },
    {
      zh: '大家越来越习惯当地的生活了。',
      en: 'Everyone is getting more and more used to local life.',
      src: allSetSrc,
    },
    {
      zh: '你越来越会做菜了。',
      en: "You're getting better and better at cooking.",
      src: allSetSrc,
    },
    {
      zh: '有了孩子以后，我越来越能理解我自己的父母了。',
      en: 'After I have my own kid, I can understand my own parents more and more.',
      src: allSetSrc,
    },
  ],
};
