/* --- AUTOGENERATED FILE -----------------------------
* If you make changes to this file delete this comment.
* Otherwise the file may be overwritten in the future.
* --------------------------------------------------- */

const { mergeLocMatchGroups, regexMatchLocs } = require('../lib/regexMatchers');

const allSetSrc = {
  type: 'website',
  url: 'https://resources.allsetlearning.com/chinese/grammar/ASGTD3L3',
  name: 'AllSet Chinese Grammar Wiki',
};

module.exports = {
  id: 'zhiqian',
  name: 'Event + 之前 / 之后',
  description:
    "Before and after can be expressed using 之前 (zhīqián) and 之后 (zhīhòu). They are in relatively the same vein as 以前/以后, except that these two are adverbs, while 之前/之后 are prepositions. Don't forget that these two are talking about before and after in terms of time.",
  sources: [allSetSrc],
  match: sentence => {
    const text = sentence.original;
    return mergeLocMatchGroups([regexMatchLocs(text, /((?:之前|之后))/)]);
  },
  examples: [
    {
      zh: '下班之前，经理给我们开了一个会议。',
      en: 'Before I got off work, the manager assembled a meeting with us.',
      src: allSetSrc,
    },
    {
      zh: '来中国之前，我的汉语水平很低。',
      en: 'Before I came to China, my Chinese was bad.',
      src: allSetSrc,
    },
    {
      zh: '吃完饭之后，他们去了一家电影院。',
      en: 'After they finished eating, they went to a movie theater.',
      src: allSetSrc,
    },
    {
      zh: '去北京之后，他和他的女朋友分手了。',
      en: 'After he went to Beijing, he broke up with his girlfriend.',
      src: allSetSrc,
    },
  ],
};
